// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Known-answer test for ML-KEM-768 (network_drivers/presentation/pqc/mlkem), the post-quantum half of
// the mlkem768x25519-sha256 / X25519MLKEM768 hybrids. The vector in mlkem_kat.h is generated by
// tools/gen_mlkem_kat.py from kyber-py (FIPS 203) - it fixes KeyGen seeds d=0..31, z=32..63 and an
// encapsulation message m, then pins (ek, dk, ct, ss). A byte-exact match here proves our independent
// KeyGen, Encaps and Decaps all agree with a reference implementation. Pure host tests.

#include "mlkem_kat.h"
#include "network_drivers/presentation/pqc/mlkem.h"
#include <string.h>
#include <unity.h>

// The fixed KeyGen seeds the KAT was generated from (tools/gen_mlkem_kat.py: d = range(0,32),
// z = range(32,64)). Not emitted into the header - reconstructed here so KeyGen is checked against
// the pinned ek/dk.
static void kat_seeds(uint8_t d[32], uint8_t z[32])
{
    for (unsigned i = 0; i < 32; i++)
    {
        d[i] = (uint8_t)i;
        z[i] = (uint8_t)(32 + i);
    }
}

void setUp()
{
}
void tearDown()
{
}

// Deterministic KeyGen(d, z) must reproduce the reference encapsulation and decapsulation keys.
void test_mlkem768_keygen_kat()
{
    uint8_t d[32];
    uint8_t z[32];
    kat_seeds(d, z);
    uint8_t ek[MLKEM768_EK_BYTES];
    uint8_t dk[MLKEM768_DK_BYTES];
    dws_mlkem768_keygen(d, z, ek, dk);
    // rho is the trailing 32 octets of ek (ByteEncode12(t) || rho); matching it isolates the G(d||k)
    // derivation from the matrix-ordering / t computation, so a failure points at exactly one of them.
    TEST_ASSERT_EQUAL_HEX8_ARRAY(kat_ek + 1152, ek + 1152, 32);
    // dk_pke = ByteEncode12(s-hat) is the first 1152 octets of dk and does NOT depend on the public
    // matrix - matching it isolates s-sampling + NTT + ByteEncode from the t = A o s + e computation.
    TEST_ASSERT_EQUAL_HEX8_ARRAY(kat_dk, dk, 1152);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(kat_ek, ek, MLKEM768_EK_BYTES);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(kat_dk, dk, MLKEM768_DK_BYTES);
}

// Decaps(dk, ct) must recover the pinned shared secret from the reference ciphertext.
void test_mlkem768_decaps_kat()
{
    uint8_t ss[MLKEM768_SS_BYTES];
    dws_mlkem768_decaps(kat_dk, kat_ct, ss);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(kat_ss, ss, MLKEM768_SS_BYTES);
}

// End-to-end initiator/responder round-trip: our KeyGen -> our Encaps -> our Decaps agrees on ss for
// a message distinct from the KAT's, so both directions interlock rather than merely matching a pin.
void test_mlkem768_roundtrip()
{
    uint8_t d[32];
    uint8_t z[32];
    kat_seeds(d, z);
    d[5] ^= 0xA5; // a different keypair than the KAT
    z[9] ^= 0x5A;
    uint8_t ek[MLKEM768_EK_BYTES];
    uint8_t dk[MLKEM768_DK_BYTES];
    dws_mlkem768_keygen(d, z, ek, dk);

    uint8_t m[MLKEM768_MSG_BYTES];
    for (unsigned i = 0; i < sizeof(m); i++)
        m[i] = (uint8_t)(i * 3 + 11);
    uint8_t ct[MLKEM768_CT_BYTES];
    uint8_t ss_enc[MLKEM768_SS_BYTES];
    TEST_ASSERT_TRUE(dws_mlkem768_encaps(ek, m, ct, ss_enc));

    uint8_t ss_dec[MLKEM768_SS_BYTES];
    dws_mlkem768_decaps(dk, ct, ss_dec);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(ss_enc, ss_dec, MLKEM768_SS_BYTES);
}

// FO implicit reject (FIPS 203 §6.3): a tampered ciphertext must NOT recover the real secret; it must
// yield the deterministic J(z || ct') reject key - same output every time, never a decrypt failure.
void test_mlkem768_decaps_implicit_reject()
{
    uint8_t bad[MLKEM768_CT_BYTES];
    memcpy(bad, kat_ct, sizeof(bad));
    bad[0] ^= 0x01; // flip one bit of the ciphertext

    uint8_t ss1[MLKEM768_SS_BYTES];
    uint8_t ss2[MLKEM768_SS_BYTES];
    dws_mlkem768_decaps(kat_dk, bad, ss1);
    dws_mlkem768_decaps(kat_dk, bad, ss2);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(ss1, ss2, MLKEM768_SS_BYTES);        // deterministic
    TEST_ASSERT_NOT_EQUAL(0, memcmp(ss1, kat_ss, MLKEM768_SS_BYTES)); // not the real secret
}

// Deterministic Encaps(ek, m) must reproduce the reference ciphertext and shared secret exactly.
void test_mlkem768_encaps_kat()
{
    uint8_t ct[MLKEM768_CT_BYTES];
    uint8_t ss[MLKEM768_SS_BYTES];
    bool ok = dws_mlkem768_encaps(kat_ek, kat_m, ct, ss);
    TEST_ASSERT_TRUE(ok);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(kat_ct, ct, MLKEM768_CT_BYTES);
    TEST_ASSERT_EQUAL_HEX8_ARRAY(kat_ss, ss, MLKEM768_SS_BYTES);
}

// A differently keyed but valid message still yields a 32-octet secret and a well-formed ciphertext
// (the shared secret must differ from the pinned one - Encaps mixes m into K via G).
void test_mlkem768_encaps_varies_with_m()
{
    uint8_t m2[MLKEM768_MSG_BYTES];
    memcpy(m2, kat_m, sizeof(m2));
    m2[0] ^= 0xFF;
    uint8_t ct[MLKEM768_CT_BYTES];
    uint8_t ss[MLKEM768_SS_BYTES];
    TEST_ASSERT_TRUE(dws_mlkem768_encaps(kat_ek, m2, ct, ss));
    TEST_ASSERT_NOT_EQUAL(0, memcmp(ss, kat_ss, MLKEM768_SS_BYTES));
    TEST_ASSERT_NOT_EQUAL(0, memcmp(ct, kat_ct, MLKEM768_CT_BYTES));
}

// FIPS 203 modulus check: an encapsulation key with an out-of-range coefficient is rejected.
void test_mlkem768_rejects_malformed_ek()
{
    uint8_t bad[MLKEM768_EK_BYTES];
    memcpy(bad, kat_ek, sizeof(bad));
    // Force the first 12-bit coefficient to 0xFFF (4095 >= q=3329).
    bad[0] = 0xFF;
    bad[1] = (uint8_t)(bad[1] | 0x0F);
    uint8_t ct[MLKEM768_CT_BYTES];
    uint8_t ss[MLKEM768_SS_BYTES];
    TEST_ASSERT_FALSE(dws_mlkem768_encaps(bad, kat_m, ct, ss));
}

int main()
{
    UNITY_BEGIN();
    RUN_TEST(test_mlkem768_encaps_kat);
    RUN_TEST(test_mlkem768_encaps_varies_with_m);
    RUN_TEST(test_mlkem768_rejects_malformed_ek);
    RUN_TEST(test_mlkem768_keygen_kat);
    RUN_TEST(test_mlkem768_decaps_kat);
    RUN_TEST(test_mlkem768_roundtrip);
    RUN_TEST(test_mlkem768_decaps_implicit_reject);
    return UNITY_END();
}
