// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by src/web/wizard/build_assets.py - DO NOT EDIT BY HAND.
// Edit the source documents under src/web/input/ and re-run the generator.

/**
 * @file html.h
 * @brief Layer 7 (Application) - embedded HTML assets (generated from src/web/input/).
 *
 * On ESP32 these const arrays live in flash (DROM) and are read directly - no
 * filesystem or heap. Edit src/web/input/ and re-run src/web/wizard/build_assets.py.
 */

#ifndef DETERMINISTICESPASYNCWEBSERVER_HTML_H
#define DETERMINISTICESPASYNCWEBSERVER_HTML_H

/** @brief Captive-portal form for WiFi credential entry (provisioning service). */
extern const char DETWS_PROV_FORM[];

/** @brief Success page shown after credentials are saved and the device reboots. */
extern const char DETWS_PROV_SAVED_HTML[];

/** @brief Self-contained WebSocket terminal page (green-phosphor CRT theme; auto ws/wss). */
extern const char DETWS_TERMINAL_PAGE[];

#endif // DETERMINISTICESPASYNCWEBSERVER_HTML_H
