// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by src/web/wizard/build_assets.py - DO NOT EDIT BY HAND.
// Edit the source documents under src/web/input/ and re-run the generator.

#include "network_drivers/application/html.h"

const char DETWS_PROV_FORM[] =
    "<!DOCTYPE html><html><head><meta name=viewport content='width=device-width'><title>WiFi setup</title></head><b"
    "ody><h2>WiFi setup</h2><form method=POST action=/save>SSID:<br><input name=ssid maxlength=32><br>Password:<br>"
    "<input name=psk type=password maxlength=63><br><br><input type=submit value=Save></form></body></html>";

const char DETWS_PROV_SAVED_HTML[] = "<html><body>Saved. Rebooting...</body></html>";

const char DETWS_TERMINAL_PAGE[] =
    "<!doctype html><html><head><meta charset=utf-8><meta name=viewport content=\"width=device-width,initial-scale="
    "1\"><title>DetWS Terminal</title><style>:root{--g:#2bb35a;--g2:#00c000;--bg:#080c08}*{box-sizing:border-box}ht"
    "ml,body{margin:0;height:100%;background:var(--bg);color:var(--g);font:14px/1.45 'Consolas','DejaVu Sans Mono',"
    "monospace}#wrap{display:flex;flex-direction:column;height:100%;position:relative}#out{flex:1;overflow:auto;pad"
    "ding:10px;white-space:pre-wrap;word-break:break-word;text-shadow:0 0 4px rgba(43,179,90,.55)}#bar{display:flex"
    ";border-top:1px solid #14401f;background:#0a0f0a}#ps{padding:8px 4px 8px 10px;color:var(--g2)}#in{flex:1;backg"
    "round:transparent;border:0;color:var(--g);font:inherit;padding:8px;outline:none}#st{padding:4px 10px;font-size"
    ":11px;color:#1c6e38;border-top:1px solid #14401f}#crt{position:absolute;inset:0;pointer-events:none;z-index:9;"
    "background:repeating-linear-gradient(rgba(0,0,0,0) 0 2px,rgba(0,0,0,.18) 3px);box-shadow:inset 0 0 120px rgba("
    "0,0,0,.6)}.e{color:#d2553a}</style></head><body><div id=wrap><div id=out></div><div id=bar><span id=ps>&gt;</s"
    "pan><input id=in autocomplete=off autofocus></div><div id=st>connecting…</div><div id=crt></div></div><script>"
    "var out=document.getElementById('out'),inp=document.getElementById('in'),st=document.getElementById('st');var "
    "hist=[],hi=0,ws,url=(location.protocol=='https:'?'wss':'ws')+'://'+location.host+location.pathname.replace(/\\"
    "/$/,'')+'/ws';function add(t,c){var b=out.scrollHeight-out.clientHeight-out.scrollTop<40;var s=document.create"
    "Element('span');if(c)s.className=c;s.textContent=t;out.appendChild(s);if(b)out.scrollTop=out.scrollHeight}func"
    "tion conn(){ws=new WebSocket(url);ws.onopen=function(){st.textContent='connected'};ws.onmessage=function(e){ad"
    "d(e.data)};ws.onclose=function(){st.textContent='disconnected — retrying…';setTimeout(conn,1000)};ws.onerror=f"
    "unction(){try{ws.close()}catch(_){}}}inp.addEventListener('keydown',function(e){if(e.key=='Enter'){var v=inp.v"
    "alue;if(v){if(ws&&ws.readyState==1){ws.send(v);add('> '+v+'\\n')}else add('> '+v+' (offline)\\n','e');hist.pus"
    "h(v);hi=hist.length}inp.value=''}else if(e.key=='ArrowUp'){if(hi>0){hi--;inp.value=hist[hi]||''}}else if(e.key"
    "=='ArrowDown'){if(hi<hist.length){hi++;inp.value=hist[hi]||''}}});conn()</script></body></html>";
