// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by src/web/wizard/build_assets.py - DO NOT EDIT BY HAND.
// Edit the source documents under src/web/input/ and re-run the generator.

/**
 * @file text.h
 * @brief Layer 7 (Application) - embedded TEXT assets (generated from src/web/input/).
 *
 * On ESP32 these const arrays live in flash (DROM) and are read directly - no
 * filesystem or heap. Edit src/web/input/ and re-run src/web/wizard/build_assets.py.
 */

#ifndef DETERMINISTICESPASYNCWEBSERVER_TEXT_H
#define DETERMINISTICESPASYNCWEBSERVER_TEXT_H

/** @brief All available Prometheus metrics; comment a value line out with a leading # to drop it. */
extern const char DETWS_METRICS_PROM[];

#endif // DETERMINISTICESPASYNCWEBSERVER_TEXT_H
