// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by src/web/wizard/build_assets.py - DO NOT EDIT BY HAND.
// Edit the source documents under src/web/input/ and re-run the generator.

#include "network_drivers/application/text.h"

const char DETWS_METRICS_PROM[] =
    "# HELP detws_uptime_seconds Device uptime in seconds.\n# TYPE detws_uptime_seconds gauge\ndetws_uptime_seconds"
    " {{uptime_seconds}}\n# HELP detws_http_requests_total Total HTTP responses sent.\n# TYPE detws_http_requests_t"
    "otal counter\ndetws_http_requests_total {{requests_total}}\n# HELP detws_http_responses_total HTTP responses b"
    "y status class.\n# TYPE detws_http_responses_total counter\ndetws_http_responses_total{class=\"2xx\"} {{resp_2"
    "xx}}\ndetws_http_responses_total{class=\"4xx\"} {{resp_4xx}}\ndetws_http_responses_total{class=\"5xx\"} {{resp"
    "_5xx}}\n# HELP detws_active_connections Currently active connection slots.\n# TYPE detws_active_connections ga"
    "uge\ndetws_active_connections {{active_conns}}\n# HELP detws_max_connections Connection slot capacity.\n# TYPE"
    " detws_max_connections gauge\ndetws_max_connections {{max_conns}}\n# HELP detws_free_heap_bytes Free heap in b"
    "ytes.\n# TYPE detws_free_heap_bytes gauge\ndetws_free_heap_bytes {{free_heap}}\n# HELP detws_min_free_heap_byt"
    "es Lowest free heap observed since boot, in bytes.\n# TYPE detws_min_free_heap_bytes gauge\ndetws_min_free_hea"
    "p_bytes {{min_free_heap}}\n# HELP detws_heap_size_bytes Total heap size, in bytes.\n# TYPE detws_heap_size_byt"
    "es gauge\ndetws_heap_size_bytes {{heap_size}}\n# HELP detws_max_alloc_heap_bytes Largest contiguous allocatabl"
    "e heap block, in bytes.\n# TYPE detws_max_alloc_heap_bytes gauge\ndetws_max_alloc_heap_bytes {{max_alloc_heap}"
    "}\n";
