// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by src/web/wizard/build_assets.py - DO NOT EDIT BY HAND.
// Edit the source documents under src/web/input/ and re-run the generator.

#include "network_drivers/application/web_assets.h"

// ---- html ----
const char DETWS_DASHBOARD_PAGE[] =
    "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\" /><meta name=\"viewport\" content=\"width=devic"
    "e-width, initial-scale=1\" /><title>Dashboard</title> <style>\n      * {\n        box-sizing: border-box;\n   "
    "   }\n      body {\n        margin: 0;\n        font-family: system-ui, \"Segoe UI\", Roboto, sans-serif;\n   "
    "     background: #0e1116;\n        color: #e6edf3;\n      }\n      header {\n        display: flex;\n        a"
    "lign-items: center;\n        gap: 10px;\n        padding: 14px 20px;\n        font-size: 18px;\n        font-w"
    "eight: 600;\n        border-bottom: 1px solid #30363d;\n      }\n      #dot {\n        width: 10px;\n        h"
    "eight: 10px;\n        border-radius: 50%;\n        background: #f85149;\n      }\n      #dot.live {\n        b"
    "ackground: #3fb950;\n      }\n      #status {\n        font-size: 13px;\n        font-weight: 400;\n        co"
    "lor: #8b949e;\n      }\n      #grid {\n        display: grid;\n        grid-template-columns: repeat(auto-fill"
    ", minmax(220px, 1fr));\n        gap: 14px;\n        padding: 18px;\n      }\n      .card {\n        background"
    ": #1b2230;\n        border: 1px solid #30363d;\n        border-radius: 10px;\n        padding: 14px;\n      }"
    "\n      .card .label {\n        margin-bottom: 8px;\n        font-size: 13px;\n        color: #8b949e;\n      "
    "}\n      .card .num {\n        font-size: 30px;\n        font-weight: 600;\n        font-variant-numeric: tabu"
    "lar-nums;\n      }\n      .card .unit {\n        margin-left: 4px;\n        font-size: 14px;\n        color: #"
    "8b949e;\n      }\n      svg {\n        display: block;\n        width: 100%;\n        height: auto;\n      }\n"
    "      svg text {\n        fill: #e6edf3;\n        font-family: inherit;\n      }\n    </style> </head><body><h"
    "eader><span id=\"dot\"></span> Dashboard <span id=\"status\"></span></header><div id=\"grid\"></div> <script>"
    "\n      (function () {\n        var NS = \"http://www.w3.org/2000/svg\";\n        var base = location.pathname"
    ".replace(/\\/+$/, \"\");\n        var grid = document.getElementById(\"grid\");\n        var dot = document.ge"
    "tElementById(\"dot\");\n        var status = document.getElementById(\"status\");\n        var widgets = {};\n"
    "\n        function clamp(f) {\n          return f < 0 ? 0 : f > 1 ? 1 : f;\n        }\n        function frac(v"
    ", mn, mx) {\n          return mx > mn ? clamp((v - mn) / (mx - mn)) : 0;\n        }\n        function fmt(v) {"
    "\n          return Math.abs(v) >= 100 ? v.toFixed(0) : v.toFixed(1);\n        }\n        function el(tag, attr"
    "s) {\n          var e = document.createElementNS(NS, tag);\n          for (var k in attrs) e.setAttribute(k, a"
    "ttrs[k]);\n          return e;\n        }\n        function polar(cx, cy, r, deg) {\n          var a = (deg * "
    "Math.PI) / 180;\n          return [cx + r * Math.cos(a), cy - r * Math.sin(a)];\n        }\n        function a"
    "rc(cx, cy, r, f) {\n          var s = polar(cx, cy, r, 180),\n            e = polar(cx, cy, r, 180 - 180 * f);"
    "\n          return \"M\" + s[0] + \" \" + s[1] + \" A\" + r + \" \" + r + \" 0 0 1 \" + e[0] + \" \" + e[1];\n"
    "        }\n\n        function card(w) {\n          var c = document.createElement(\"div\");\n          c.class"
    "Name = \"card\";\n          var lab = document.createElement(\"div\");\n          lab.className = \"label\";\n"
    "          lab.textContent = w.label;\n          c.appendChild(lab);\n          var upd;\n          if (w.type "
    "=== \"gauge\") {\n            var g = el(\"svg\", { viewBox: \"0 0 120 72\" });\n            g.appendChild(el("
    "\"path\", { d: arc(60, 62, 50, 1), fill: \"none\", stroke: \"#30363d\", \"stroke-width\": 10, \"stroke-linecap"
    "\": \"round\" }));\n            var gv = el(\"path\", { d: arc(60, 62, 50, 0), fill: \"none\", stroke: \"#3fb9"
    "50\", \"stroke-width\": 10, \"stroke-linecap\": \"round\" });\n            g.appendChild(gv);\n            var"
    " gt = el(\"text\", { x: 60, y: 58, \"text-anchor\": \"middle\", \"font-size\": 16, \"font-weight\": 600 });\n "
    "           gt.textContent = \"-\";\n            g.appendChild(gt);\n            c.appendChild(g);\n           "
    " upd = function (v) {\n              gv.setAttribute(\"d\", arc(60, 62, 50, frac(v, w.min, w.max)));\n        "
    "      gt.textContent = fmt(v) + w.unit;\n            };\n          } else if (w.type === \"bar\") {\n         "
    "   var b = el(\"svg\", { viewBox: \"0 0 200 40\" });\n            b.appendChild(el(\"rect\", { x: 0, y: 16, wi"
    "dth: 200, height: 12, rx: 6, fill: \"#30363d\" }));\n            var bf = el(\"rect\", { x: 0, y: 16, width: 0"
    ", height: 12, rx: 6, fill: \"#3fb950\" });\n            b.appendChild(bf);\n            var bt = el(\"text\", "
    "{ x: 0, y: 11, \"font-size\": 12 });\n            bt.textContent = \"-\";\n            b.appendChild(bt);\n   "
    "         c.appendChild(b);\n            upd = function (v) {\n              bf.setAttribute(\"width\", 200 * f"
    "rac(v, w.min, w.max));\n              bt.textContent = fmt(v) + w.unit;\n            };\n          } else if ("
    "w.type === \"sparkline\") {\n            var s = el(\"svg\", { viewBox: \"0 0 200 50\" });\n            var pl"
    " = el(\"polyline\", { fill: \"none\", stroke: \"#3fb950\", \"stroke-width\": 2, points: \"\" });\n            "
    "s.appendChild(pl);\n            c.appendChild(s);\n            var sn = document.createElement(\"div\");\n    "
    "        sn.className = \"num\";\n            sn.textContent = \"-\";\n            c.appendChild(sn);\n        "
    "    var hist = [];\n            upd = function (v) {\n              hist.push(v);\n              if (hist.leng"
    "th > 40) hist.shift();\n              var pts = hist\n                .map(function (y, i) {\n                "
    "  return (200 * i) / 39 + \",\" + (50 - 50 * frac(y, w.min, w.max));\n                })\n                .joi"
    "n(\" \");\n              pl.setAttribute(\"points\", pts);\n              sn.textContent = fmt(v) + \" \" + w."
    "unit;\n            };\n          } else {\n            var n = document.createElement(\"div\");\n            n"
    ".className = \"num\";\n            var tn = document.createTextNode(\"-\");\n            n.appendChild(tn);\n "
    "           var u = document.createElement(\"span\");\n            u.className = \"unit\";\n            u.textC"
    "ontent = w.unit;\n            n.appendChild(u);\n            c.appendChild(n);\n            upd = function (v)"
    " {\n              tn.nodeValue = fmt(v);\n            };\n          }\n          grid.appendChild(c);\n       "
    "   return upd;\n        }\n\n        fetch(base + \"/layout\")\n          .then(function (r) {\n            re"
    "turn r.json();\n          })\n          .then(function (list) {\n            list.forEach(function (w) {\n    "
    "          widgets[w.key] = card(w);\n            });\n            var es = new EventSource(base + \"/stream\")"
    ";\n            es.onopen = function () {\n              dot.className = \"live\";\n              status.textCo"
    "ntent = \"live\";\n            };\n            es.onerror = function () {\n              dot.className = \"\";"
    "\n              status.textContent = \"reconnecting...\";\n            };\n            es.onmessage = function"
    " (ev) {\n              try {\n                var d = JSON.parse(ev.data);\n                for (var k in d) i"
    "f (widgets[k]) widgets[k](d[k]);\n              } catch (e) {}\n            };\n          });\n      })();\n  "
    "  </script> </body></html>";

const char DETWS_PROV_FORM[] =
    "<!DOCTYPE html><html><head><meta name=viewport content='width=device-width'><title>WiFi setup</title></head><b"
    "ody><h2>WiFi setup</h2><form method=POST action=/save>SSID:<br><input name=ssid maxlength=32><br>Password:<br>"
    "<input name=psk type=password maxlength=63><br><br><input type=submit value=Save></form></body></html>";

const char DETWS_PROV_SAVED_HTML[] = "<html><body>Saved. Rebooting...</body></html>";

const char DETWS_TERMINAL_PAGE[] =
    "<!doctype html><html><head><meta charset=utf-8><meta name=viewport content=\"width=device-width,initial-scale="
    "1\"><title>DetWS Terminal</title><style>:root{--g:#2bb35a;--g2:#00c000;--bg:#080c08}*{box-sizing:border-box}ht"
    "ml,body{margin:0;height:100%;background:var(--bg);color:var(--g);font:14px/1.45 'Consolas','DejaVu Sans Mono',"
    "monospace}#wrap{display:flex;flex-direction:column;height:100%;position:relative}#out{flex:1;overflow:auto;pad"
    "ding:10px;white-space:pre-wrap;word-break:break-word;text-shadow:0 0 4px rgba(43,179,90,.55)}#bar{display:flex"
    ";border-top:1px solid #14401f;background:#0a0f0a}#ps{padding:8px 4px 8px 10px;color:var(--g2)}#in{flex:1;backg"
    "round:transparent;border:0;color:var(--g);font:inherit;padding:8px;outline:none}#st{padding:4px 10px;font-size"
    ":11px;color:#1c6e38;border-top:1px solid #14401f}#crt{position:absolute;inset:0;pointer-events:none;z-index:9;"
    "background:repeating-linear-gradient(rgba(0,0,0,0) 0 2px,rgba(0,0,0,.18) 3px);box-shadow:inset 0 0 120px rgba("
    "0,0,0,.6)}.e{color:#d2553a}</style></head><body><div id=wrap><div id=out></div><div id=bar><span id=ps>&gt;</s"
    "pan><input id=in autocomplete=off autofocus></div><div id=st>connecting…</div><div id=crt></div></div><script>"
    "var out=document.getElementById('out'),inp=document.getElementById('in'),st=document.getElementById('st');var "
    "hist=[],hi=0,ws,url=(location.protocol=='https:'?'wss':'ws')+'://'+location.host+location.pathname.replace(/\\"
    "/$/,'')+'/ws';function add(t,c){var b=out.scrollHeight-out.clientHeight-out.scrollTop<40;var s=document.create"
    "Element('span');if(c)s.className=c;s.textContent=t;out.appendChild(s);if(b)out.scrollTop=out.scrollHeight}func"
    "tion conn(){ws=new WebSocket(url);ws.onopen=function(){st.textContent='connected'};ws.onmessage=function(e){ad"
    "d(e.data)};ws.onclose=function(){st.textContent='disconnected — retrying…';setTimeout(conn,1000)};ws.onerror=f"
    "unction(){try{ws.close()}catch(_){}}}inp.addEventListener('keydown',function(e){if(e.key=='Enter'){var v=inp.v"
    "alue;if(v){if(ws&&ws.readyState==1){ws.send(v);add('> '+v+'\\n')}else add('> '+v+' (offline)\\n','e');hist.pus"
    "h(v);hi=hist.length}inp.value=''}else if(e.key=='ArrowUp'){if(hi>0){hi--;inp.value=hist[hi]||''}}else if(e.key"
    "=='ArrowDown'){if(hi<hist.length){hi++;inp.value=hist[hi]||''}}});conn()</script></body></html>";

// ---- json ----
const char DETWS_STATS_JSON[] =
    "{\"uptime_ms\":{{uptime_ms}},\"requests\":{{requests}},\"http_2xx\":{{http_2xx}},\"http_4xx\":{{http_4xx}},\"h"
    "ttp_5xx\":{{http_5xx}},\"active_conns\":{{active_conns}},\"free_heap\":{{free_heap}}}";

// ---- text ----
const char DETWS_METRICS_PROM[] =
    "# HELP detws_uptime_seconds Device uptime in seconds.\n# TYPE detws_uptime_seconds gauge\ndetws_uptime_seconds"
    " {{uptime_seconds}}\n# HELP detws_http_requests_total Total HTTP responses sent.\n# TYPE detws_http_requests_t"
    "otal counter\ndetws_http_requests_total {{requests_total}}\n# HELP detws_http_responses_total HTTP responses b"
    "y status class.\n# TYPE detws_http_responses_total counter\ndetws_http_responses_total{class=\"2xx\"} {{resp_2"
    "xx}}\ndetws_http_responses_total{class=\"4xx\"} {{resp_4xx}}\ndetws_http_responses_total{class=\"5xx\"} {{resp"
    "_5xx}}\n# HELP detws_active_connections Currently active connection slots.\n# TYPE detws_active_connections ga"
    "uge\ndetws_active_connections {{active_conns}}\n# HELP detws_max_connections Connection slot capacity.\n# TYPE"
    " detws_max_connections gauge\ndetws_max_connections {{max_conns}}\n# HELP detws_free_heap_bytes Free heap in b"
    "ytes.\n# TYPE detws_free_heap_bytes gauge\ndetws_free_heap_bytes {{free_heap}}\n# HELP detws_min_free_heap_byt"
    "es Lowest free heap observed since boot, in bytes.\n# TYPE detws_min_free_heap_bytes gauge\ndetws_min_free_hea"
    "p_bytes {{min_free_heap}}\n# HELP detws_heap_size_bytes Total heap size, in bytes.\n# TYPE detws_heap_size_byt"
    "es gauge\ndetws_heap_size_bytes {{heap_size}}\n# HELP detws_max_alloc_heap_bytes Largest contiguous allocatabl"
    "e heap block, in bytes.\n# TYPE detws_max_alloc_heap_bytes gauge\ndetws_max_alloc_heap_bytes {{max_alloc_heap}"
    "}\n";
