// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Streamlined NTRU Prime sntrup761 KEM (network_drivers/presentation/pqc/sntrup761): the second PQC
// KEM OpenSSH ships, used by sntrup761x25519-sha512@openssh.com. Decapsulation is pinned to a KAT
// generated by the OpenSSH reference (dec(SK, CT) == SS - conformance), and a keypair/enc/dec
// round-trip proves the responder Encaps and the initiator KeyGen+Decaps agree. Enc conformance
// against a real peer is the HW OpenSSH interop; here the reference KAT anchors Decaps.

#include "network_drivers/presentation/pqc/sntrup761.h"

#include "sntrup761_kat.h"
#include <stdint.h>
#include <string.h>
#include <unity.h>

// The CSPRNG seam (forward-declared in sntrup761.cpp): a deterministic test source so the round-trip
// is reproducible. sntrup761 interop does not depend on how r/keys are drawn, only that they are valid.
static uint32_t s_rng = 0xA5A5F00Du;

// KeyGen's g-draw retry hook: while > 0, ssh_rng_fill returns bytes that make Small_random's ternary
// map (see sntrup761.cpp) produce coefficient 0 rather than drawing from the LCG, and decrements by
// one per call. Left at 0 for every other test, so it is a no-op there.
static int s_force_zero_calls = 0;
void ssh_rng_fill(uint8_t *b, size_t n)
{
    if (s_force_zero_calls > 0)
    {
        --s_force_zero_calls;
        for (size_t i = 0; i < n; ++i)
            b[i] = 0;
        if (n >= 4)
            b[3] = 0x20; // u & 0x3fffffff == 0x20000000 -> (u30*3)>>30 == 1 -> ternary coefficient 0
        return;
    }
    for (size_t i = 0; i < n; ++i)
    {
        s_rng = s_rng * 1103515245u + 12345u;
        b[i] = (uint8_t)(s_rng >> 16);
    }
}

void setUp()
{
}
void tearDown()
{
}

// dec(SK, CT) recovers the exact shared secret the OpenSSH reference produced (byte-exact conformance).
void test_sntrup761_decaps_kat()
{
    uint8_t ss[DWS_SNTRUP761_SS_BYTES];
    dws_sntrup761_dec(KAT_SK, KAT_CT, ss);
    TEST_ASSERT_EQUAL_MEMORY(KAT_SS, ss, DWS_SNTRUP761_SS_BYTES);
}

// keypair -> enc -> dec recovers the same secret across many keypairs (responder + initiator agree).
void test_sntrup761_roundtrip()
{
    for (int t = 0; t < 20; ++t)
    {
        uint8_t pk[DWS_SNTRUP761_PK_BYTES], sk[DWS_SNTRUP761_SK_BYTES];
        uint8_t ct[DWS_SNTRUP761_CT_BYTES], ss1[DWS_SNTRUP761_SS_BYTES], ss2[DWS_SNTRUP761_SS_BYTES];
        dws_sntrup761_keypair(pk, sk);
        dws_sntrup761_enc(pk, ct, ss1);
        dws_sntrup761_dec(sk, ct, ss2);
        TEST_ASSERT_EQUAL_MEMORY(ss1, ss2, DWS_SNTRUP761_SS_BYTES);
    }
}

// A tampered ciphertext implicit-rejects (FO): no crash, and a deterministic secret != the valid one.
void test_sntrup761_implicit_reject()
{
    uint8_t pk[DWS_SNTRUP761_PK_BYTES], sk[DWS_SNTRUP761_SK_BYTES];
    uint8_t ct[DWS_SNTRUP761_CT_BYTES], good[DWS_SNTRUP761_SS_BYTES], bad[DWS_SNTRUP761_SS_BYTES];
    dws_sntrup761_keypair(pk, sk);
    dws_sntrup761_enc(pk, ct, good);
    ct[0] = (uint8_t)(ct[0] ^ 0xff); // corrupt the ciphertext
    dws_sntrup761_dec(sk, ct, bad);
    TEST_ASSERT_TRUE(memcmp(good, bad, DWS_SNTRUP761_SS_BYTES) != 0);
}

// KeyGen draws g and retries while it is non-invertible mod 3 (R3_recip != 0). The all-zero
// polynomial is never invertible (0 has no multiplicative inverse in any ring), so forcing the first
// draw to zero deterministically exercises the retry path; KeyGen then re-draws from the normal
// stream and succeeds, producing a keypair that still round-trips correctly end to end.
void test_sntrup761_keygen_retries_on_noninvertible_g()
{
    s_force_zero_calls = 761; // p = 761 (see sntrup761.h): forces every g coefficient to 0
    uint8_t pk[DWS_SNTRUP761_PK_BYTES], sk[DWS_SNTRUP761_SK_BYTES];
    uint8_t ct[DWS_SNTRUP761_CT_BYTES], ss1[DWS_SNTRUP761_SS_BYTES], ss2[DWS_SNTRUP761_SS_BYTES];
    dws_sntrup761_keypair(pk, sk);
    TEST_ASSERT_EQUAL_INT(0, s_force_zero_calls); // the forced draw was actually consumed
    dws_sntrup761_enc(pk, ct, ss1);
    dws_sntrup761_dec(sk, ct, ss2);
    TEST_ASSERT_EQUAL_MEMORY(ss1, ss2, DWS_SNTRUP761_SS_BYTES);
}

int main()
{
    UNITY_BEGIN();
    RUN_TEST(test_sntrup761_decaps_kat);
    RUN_TEST(test_sntrup761_roundtrip);
    RUN_TEST(test_sntrup761_implicit_reject);
    RUN_TEST(test_sntrup761_keygen_retries_on_noninvertible_g);
    return UNITY_END();
}
