// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Unit tests for the IKEv2 (RFC 7296) message + payload codec (services/ikev2): the 28-octet header, the
// generic payload chain walker, the SA -> proposal -> transform tree (with the key-length attribute),
// KE, Nonce, Notify, Delete, IDi/IDr, AUTH, TSi/TSr, and the SK envelope. The golden byte vectors were
// generated by scapy's IKEv2 codec (an independent implementation) and the key-length transform
// attribute was verified against scapy's decoder.

#include "services/ikev2/ikev2.h"
#include <string.h>
#include <unity.h>
#include <vector>

void setUp()
{
}
void tearDown()
{
}

// ── scapy-generated golden vectors ─────────────────────────────────────────────────────────────

// Bare IKE header: init SPI 11..88, resp SPI 0, next=None, ver 2.0, IKE_SA_INIT, Initiator, msgid 0.
static const uint8_t GV_HDR[] = {0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                 0x00, 0x00, 0x00, 0x20, 0x22, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1c};
// KE: next=Nonce, D-H group 14 (MODP2048), 8 bytes of key data.
static const uint8_t GV_KE[] = {0x28, 0x00, 0x00, 0x10, 0x00, 0x0e, 0x00, 0x00,
                                0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa};
// Nonce: next=None, 16-byte nonce 0x00..0x0f.
static const uint8_t GV_NONCE[] = {0x00, 0x00, 0x00, 0x14, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05,
                                   0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f};
// Notify: next=None, proto 0, no SPI, type 16388, 4 bytes.
static const uint8_t GV_NOTIFY[] = {0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x40, 0x04, 0xde, 0xad, 0xbe, 0xef};
// Delete: next=None, proto 1 (IKE), spisize 0, 0 SPIs.
static const uint8_t GV_DELETE[] = {0x00, 0x00, 0x00, 0x08, 0x01, 0x00, 0x00, 0x00};
// SA: next=KE, one IKE proposal, transforms ENCR AES-CBC + PRF HMAC-SHA2-256 (no attributes).
static const uint8_t GV_SA[] = {0x22, 0x00, 0x00, 0x1c, 0x00, 0x00, 0x00, 0x18, 0x01, 0x01, 0x00, 0x02, 0x03, 0x00,
                                0x00, 0x08, 0x01, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x08, 0x02, 0x00, 0x00, 0x05};
// SA with the first transform carrying a 256-bit key-length attribute (80 0e 01 00).
static const uint8_t GV_SA_KEYLEN[] = {0x22, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x1c, 0x01, 0x01, 0x00,
                                       0x02, 0x03, 0x00, 0x00, 0x0c, 0x01, 0x00, 0x00, 0x0c, 0x80, 0x0e,
                                       0x01, 0x00, 0x00, 0x00, 0x00, 0x08, 0x02, 0x00, 0x00, 0x05};
// Full IKE_SA_INIT: header (next=SA, len 92) + SA + KE + Nonce.
static const uint8_t GV_FULL[] = {
    0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 0x20, 0x22,
    0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x5c, 0x22, 0x00, 0x00, 0x1c, 0x00, 0x00, 0x00, 0x18, 0x01, 0x01,
    0x00, 0x02, 0x03, 0x00, 0x00, 0x08, 0x01, 0x00, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x08, 0x02, 0x00, 0x00, 0x05, 0x28,
    0x00, 0x00, 0x10, 0x00, 0x0e, 0x00, 0x00, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x00, 0x00, 0x00, 0x14,
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f};

static void fill_hdr(IkeHeader *h, IkePayloadType next, uint32_t len)
{
    memset(h, 0, sizeof(*h));
    for (int i = 0; i < 8; i++)
        h->init_spi[i] = (uint8_t)((i + 1) * 0x11); // 0x11..0x88
    h->next_payload = next;
    h->version = DWS_IKE_VERSION;
    h->exchange = IkeExchange::IKE_SA_INIT;
    h->flags = DWS_IKE_FLAG_INITIATOR;
    h->message_id = 0;
    h->length = len;
}

// ── header ───────────────────────────────────────────────────────────────────────────────────

void test_hdr_build()
{
    uint8_t buf[64];
    IkeHeader h;
    fill_hdr(&h, IkePayloadType::IKE_PL_NONE, 28);
    size_t n = dws_ike_hdr_build(buf, sizeof(buf), &h);
    TEST_ASSERT_EQUAL_size_t(28, n);
    TEST_ASSERT_EQUAL_MEMORY(GV_HDR, buf, 28);
    // overflow fails closed
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_hdr_build(buf, 27, &h));
}

void test_hdr_parse()
{
    IkeHeader h;
    TEST_ASSERT_TRUE(dws_ike_hdr_parse(GV_HDR, sizeof(GV_HDR), &h));
    TEST_ASSERT_EQUAL_UINT8(0x11, h.init_spi[0]);
    TEST_ASSERT_EQUAL_UINT8(0x88, h.init_spi[7]);
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_NONE, h.next_payload);
    TEST_ASSERT_EQUAL_UINT8(DWS_IKE_VERSION, h.version);
    TEST_ASSERT_EQUAL_UINT8(IkeExchange::IKE_SA_INIT, h.exchange);
    TEST_ASSERT_EQUAL_UINT8(DWS_IKE_FLAG_INITIATOR, h.flags);
    TEST_ASSERT_EQUAL_UINT32(0, h.message_id);
    TEST_ASSERT_EQUAL_UINT32(28, h.length);
    // truncated header -> false
    TEST_ASSERT_FALSE(dws_ike_hdr_parse(GV_HDR, 27, &h));
}

void test_hdr_set_length()
{
    uint8_t buf[64];
    IkeHeader h;
    fill_hdr(&h, IkePayloadType::IKE_PL_SA, 0); // placeholder length
    dws_ike_hdr_build(buf, sizeof(buf), &h);
    TEST_ASSERT_TRUE(dws_ike_set_length(buf, sizeof(buf), 92));
    IkeHeader r;
    TEST_ASSERT_TRUE(dws_ike_hdr_parse(buf, 28, &r));
    TEST_ASSERT_EQUAL_UINT32(92, r.length);
}

// ── individual payloads ────────────────────────────────────────────────────────────────────────

void test_ke()
{
    uint8_t buf[64];
    uint8_t data[8];
    memset(data, 0xaa, sizeof(data));
    size_t n = dws_ike_ke_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONCE, IKE_DH_MODP2048, data, sizeof(data));
    TEST_ASSERT_EQUAL_size_t(sizeof(GV_KE), n);
    TEST_ASSERT_EQUAL_MEMORY(GV_KE, buf, sizeof(GV_KE));
    // parse the body (after the 4-byte generic header)
    uint16_t group = 0;
    const uint8_t *d = nullptr;
    size_t dl = 0;
    TEST_ASSERT_TRUE(dws_ike_ke_parse(GV_KE + 4, sizeof(GV_KE) - 4, &group, &d, &dl));
    TEST_ASSERT_EQUAL_UINT16(IKE_DH_MODP2048, group);
    TEST_ASSERT_EQUAL_size_t(8, dl);
    TEST_ASSERT_EQUAL_MEMORY(data, d, 8);
}

void test_nonce()
{
    uint8_t buf[64];
    uint8_t nonce[16];
    for (int i = 0; i < 16; i++)
        nonce[i] = (uint8_t)i;
    size_t n = dws_ike_nonce_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, nonce, sizeof(nonce));
    TEST_ASSERT_EQUAL_size_t(sizeof(GV_NONCE), n);
    TEST_ASSERT_EQUAL_MEMORY(GV_NONCE, buf, sizeof(GV_NONCE));
}

void test_notify()
{
    uint8_t buf[64];
    const uint8_t data[] = {0xde, 0xad, 0xbe, 0xef};
    size_t n = dws_ike_notify_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IkeProtocol::IKE_PROTO_NONE, nullptr,
                                    0, 16388, data, sizeof(data));
    TEST_ASSERT_EQUAL_size_t(sizeof(GV_NOTIFY), n);
    TEST_ASSERT_EQUAL_MEMORY(GV_NOTIFY, buf, sizeof(GV_NOTIFY));
    // parse
    IkeProtocol proto = IkeProtocol::IKE_PROTO_ESP;
    uint8_t ss = 0xff;
    uint16_t type = 0;
    const uint8_t *spi = (const uint8_t *)1, *d = nullptr;
    size_t dl = 0;
    TEST_ASSERT_TRUE(dws_ike_notify_parse(GV_NOTIFY + 4, sizeof(GV_NOTIFY) - 4, &proto, &type, &spi, &ss, &d, &dl));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeProtocol::IKE_PROTO_NONE, (uint8_t)proto);
    TEST_ASSERT_EQUAL_UINT8(0, ss);
    TEST_ASSERT_EQUAL_UINT16(16388, type);
    TEST_ASSERT_NULL(spi);
    TEST_ASSERT_EQUAL_size_t(4, dl);
    TEST_ASSERT_EQUAL_MEMORY(data, d, 4);
}

void test_delete()
{
    uint8_t buf[32];
    size_t n =
        dws_ike_delete_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IkeProtocol::IKE_PROTO_IKE, 0, nullptr, 0);
    TEST_ASSERT_EQUAL_size_t(sizeof(GV_DELETE), n);
    TEST_ASSERT_EQUAL_MEMORY(GV_DELETE, buf, sizeof(GV_DELETE));
    IkeProtocol proto = IkeProtocol::IKE_PROTO_NONE;
    uint8_t ss = 0xff;
    uint16_t num = 0xff;
    const uint8_t *spis = (const uint8_t *)1;
    TEST_ASSERT_TRUE(dws_ike_delete_parse(GV_DELETE + 4, sizeof(GV_DELETE) - 4, &proto, &ss, &num, &spis));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeProtocol::IKE_PROTO_IKE, (uint8_t)proto);
    TEST_ASSERT_EQUAL_UINT8(0, ss);
    TEST_ASSERT_EQUAL_UINT16(0, num);
    TEST_ASSERT_NULL(spis);
}

// ── SA / proposal / transform ──────────────────────────────────────────────────────────────────

void test_sa_build_no_keylen()
{
    uint8_t buf[64];
    IkeTransform tr[2] = {{IkeTransformType::IKE_TRANSFORM_ENCR, IKE_ENCR_AES_CBC, -1},
                          {IkeTransformType::IKE_TRANSFORM_PRF, IKE_PRF_HMAC_SHA2_256, -1}};
    size_t n =
        dws_ike_sa_build(buf, sizeof(buf), IkePayloadType::IKE_PL_KE, 1, IkeProtocol::IKE_PROTO_IKE, nullptr, 0, tr, 2);
    TEST_ASSERT_EQUAL_size_t(sizeof(GV_SA), n);
    TEST_ASSERT_EQUAL_MEMORY(GV_SA, buf, sizeof(GV_SA));
}

void test_sa_build_keylen()
{
    uint8_t buf[64];
    IkeTransform tr[2] = {{IkeTransformType::IKE_TRANSFORM_ENCR, IKE_ENCR_AES_CBC, 256},
                          {IkeTransformType::IKE_TRANSFORM_PRF, IKE_PRF_HMAC_SHA2_256, -1}};
    size_t n =
        dws_ike_sa_build(buf, sizeof(buf), IkePayloadType::IKE_PL_KE, 1, IkeProtocol::IKE_PROTO_IKE, nullptr, 0, tr, 2);
    TEST_ASSERT_EQUAL_size_t(sizeof(GV_SA_KEYLEN), n);
    TEST_ASSERT_EQUAL_MEMORY(GV_SA_KEYLEN, buf, sizeof(GV_SA_KEYLEN));
}

void test_sa_parse()
{
    // parse the SA body (proposal area, after the 4-byte generic header) from the keylen vector
    IkeProposalRef prop;
    TEST_ASSERT_TRUE(dws_ike_sa_first_proposal(GV_SA_KEYLEN + 4, sizeof(GV_SA_KEYLEN) - 4, &prop));
    TEST_ASSERT_EQUAL_UINT8(1, prop.proposal_num);
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeProtocol::IKE_PROTO_IKE, (uint8_t)prop.protocol_id);
    TEST_ASSERT_EQUAL_UINT8(0, prop.spi_size);
    TEST_ASSERT_EQUAL_UINT8(2, prop.num_transforms);
    TEST_ASSERT_TRUE(prop.last);

    IkeTransformIter it;
    IkeTransformRef t;
    dws_ike_transform_iter_init(&it, &prop);
    TEST_ASSERT_TRUE(dws_ike_transform_next(&it, &t));
    TEST_ASSERT_EQUAL_UINT8(IkeTransformType::IKE_TRANSFORM_ENCR, t.type);
    TEST_ASSERT_EQUAL_UINT16(IKE_ENCR_AES_CBC, t.id);
    TEST_ASSERT_EQUAL_INT32(256, t.key_length);
    TEST_ASSERT_FALSE(t.last);
    TEST_ASSERT_TRUE(dws_ike_transform_next(&it, &t));
    TEST_ASSERT_EQUAL_UINT8(IkeTransformType::IKE_TRANSFORM_PRF, t.type);
    TEST_ASSERT_EQUAL_UINT16(IKE_PRF_HMAC_SHA2_256, t.id);
    TEST_ASSERT_EQUAL_INT32(-1, t.key_length); // absent
    TEST_ASSERT_TRUE(t.last);
    TEST_ASSERT_FALSE(dws_ike_transform_next(&it, &t)); // end
}

// ── ID / AUTH / CERT ───────────────────────────────────────────────────────────────────────────

void test_id_auth()
{
    uint8_t buf[64];
    const char *fqdn = "vpn.example";
    size_t n = dws_ike_id_build(buf, sizeof(buf), IkePayloadType::IKE_PL_AUTH, IkeIdType::IKE_ID_FQDN,
                                (const uint8_t *)fqdn, 11);
    TEST_ASSERT_EQUAL_size_t(4 + 4 + 11, n);
    // generic header: next=AUTH(39), len; body: id_type + 3 reserved + data
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_AUTH, buf[0]);
    IkeIdType id_type = IkeIdType::IKE_ID_FQDN;
    const uint8_t *d = nullptr;
    size_t dl = 0;
    TEST_ASSERT_TRUE(dws_ike_id_parse(buf + 4, n - 4, &id_type, &d, &dl));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeIdType::IKE_ID_FQDN, (uint8_t)id_type);
    TEST_ASSERT_EQUAL_size_t(11, dl);
    TEST_ASSERT_EQUAL_MEMORY(fqdn, d, 11);

    const uint8_t sig[] = {0x01, 0x02, 0x03, 0x04};
    n = dws_ike_auth_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IkeAuthMethod::IKE_AUTH_PSK, sig,
                           sizeof(sig));
    IkeAuthMethod method = IkeAuthMethod::IKE_AUTH_PSK;
    TEST_ASSERT_TRUE(dws_ike_auth_parse(buf + 4, n - 4, &method, &d, &dl));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeAuthMethod::IKE_AUTH_PSK, (uint8_t)method);
    TEST_ASSERT_EQUAL_size_t(4, dl);
    TEST_ASSERT_EQUAL_MEMORY(sig, d, 4);
}

// ── traffic selectors ──────────────────────────────────────────────────────────────────────────

void test_ts()
{
    uint8_t buf[64];
    const uint8_t start[] = {10, 0, 0, 0};
    const uint8_t end[] = {10, 0, 0, 255};
    IkeTrafficSelector sel = {IkeTsType::IKE_TS_IPV4_ADDR_RANGE, 0, 0, 65535, start, end, 4};
    size_t n = dws_ike_ts_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, &sel, 1);
    // generic(4) + num/res(4) + selector(8 + 2*4) = 24
    TEST_ASSERT_EQUAL_size_t(24, n);
    TEST_ASSERT_EQUAL_UINT8(1, dws_ike_ts_count(buf + 4, n - 4));
    IkeTrafficSelector got;
    TEST_ASSERT_TRUE(dws_ike_ts_get(buf + 4, n - 4, 0, &got));
    TEST_ASSERT_EQUAL_UINT8(IkeTsType::IKE_TS_IPV4_ADDR_RANGE, got.ts_type);
    TEST_ASSERT_EQUAL_UINT16(0, got.start_port);
    TEST_ASSERT_EQUAL_UINT16(65535, got.end_port);
    TEST_ASSERT_EQUAL_size_t(4, got.addr_len);
    TEST_ASSERT_EQUAL_MEMORY(start, got.start_addr, 4);
    TEST_ASSERT_EQUAL_MEMORY(end, got.end_addr, 4);
    TEST_ASSERT_FALSE(dws_ike_ts_get(buf + 4, n - 4, 1, &got)); // out of range
}

// ── SK envelope framing ────────────────────────────────────────────────────────────────────────

void test_sk_frame()
{
    uint8_t buf[64];
    uint8_t iv[16], ct[8], icv[16];
    memset(iv, 0x11, sizeof(iv));
    memset(ct, 0x22, sizeof(ct));
    memset(icv, 0x33, sizeof(icv));
    size_t n = dws_ike_sk_build(buf, sizeof(buf), IkePayloadType::IKE_PL_IDI, iv, sizeof(iv), ct, sizeof(ct), icv,
                                sizeof(icv));
    TEST_ASSERT_EQUAL_size_t(4 + 16 + 8 + 16, n);
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_IDI, buf[0]);
    const uint8_t *piv = nullptr, *pct = nullptr, *picv = nullptr;
    size_t ctl = 0;
    TEST_ASSERT_TRUE(dws_ike_sk_parse(buf + 4, n - 4, 16, 16, &piv, &pct, &ctl, &picv));
    TEST_ASSERT_EQUAL_MEMORY(iv, piv, 16);
    TEST_ASSERT_EQUAL_size_t(8, ctl);
    TEST_ASSERT_EQUAL_MEMORY(ct, pct, 8);
    TEST_ASSERT_EQUAL_MEMORY(icv, picv, 16);
    // too short for iv+icv -> false
    TEST_ASSERT_FALSE(dws_ike_sk_parse(buf + 4, 20, 16, 16, &piv, &pct, &ctl, &picv));
}

// ── full message + chain walk ──────────────────────────────────────────────────────────────────

void test_full_build()
{
    uint8_t buf[128];
    IkeHeader h;
    fill_hdr(&h, IkePayloadType::IKE_PL_SA, 0);
    size_t off = dws_ike_hdr_build(buf, sizeof(buf), &h);
    IkeTransform tr[2] = {{IkeTransformType::IKE_TRANSFORM_ENCR, IKE_ENCR_AES_CBC, -1},
                          {IkeTransformType::IKE_TRANSFORM_PRF, IKE_PRF_HMAC_SHA2_256, -1}};
    off += dws_ike_sa_build(buf + off, sizeof(buf) - off, IkePayloadType::IKE_PL_KE, 1, IkeProtocol::IKE_PROTO_IKE,
                            nullptr, 0, tr, 2);
    uint8_t ke[8];
    memset(ke, 0xaa, sizeof(ke));
    off +=
        dws_ike_ke_build(buf + off, sizeof(buf) - off, IkePayloadType::IKE_PL_NONCE, IKE_DH_MODP2048, ke, sizeof(ke));
    uint8_t nonce[16];
    for (int i = 0; i < 16; i++)
        nonce[i] = (uint8_t)i;
    off += dws_ike_nonce_build(buf + off, sizeof(buf) - off, IkePayloadType::IKE_PL_NONE, nonce, sizeof(nonce));
    TEST_ASSERT_TRUE(dws_ike_set_length(buf, sizeof(buf), (uint32_t)off));
    TEST_ASSERT_EQUAL_size_t(sizeof(GV_FULL), off);
    TEST_ASSERT_EQUAL_MEMORY(GV_FULL, buf, sizeof(GV_FULL));
}

void test_full_chain_walk()
{
    IkeHeader h;
    TEST_ASSERT_TRUE(dws_ike_hdr_parse(GV_FULL, sizeof(GV_FULL), &h));
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_SA, h.next_payload);
    TEST_ASSERT_EQUAL_UINT32(sizeof(GV_FULL), h.length);

    IkePayloadIter it;
    dws_ike_payload_iter_init(&it, h.next_payload, GV_FULL + DWS_IKE_HDR_LEN, sizeof(GV_FULL) - DWS_IKE_HDR_LEN);
    IkePayload pl;

    TEST_ASSERT_TRUE(dws_ike_payload_next(&it, &pl));
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_SA, pl.type);
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_KE, pl.next_payload);
    IkeProposalRef prop;
    TEST_ASSERT_TRUE(dws_ike_sa_first_proposal(pl.body, pl.body_len, &prop));
    TEST_ASSERT_EQUAL_UINT8(2, prop.num_transforms);

    TEST_ASSERT_TRUE(dws_ike_payload_next(&it, &pl));
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_KE, pl.type);
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_NONCE, pl.next_payload);
    uint16_t group = 0;
    const uint8_t *d = nullptr;
    size_t dl = 0;
    TEST_ASSERT_TRUE(dws_ike_ke_parse(pl.body, pl.body_len, &group, &d, &dl));
    TEST_ASSERT_EQUAL_UINT16(IKE_DH_MODP2048, group);
    TEST_ASSERT_EQUAL_size_t(8, dl);

    TEST_ASSERT_TRUE(dws_ike_payload_next(&it, &pl));
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_NONCE, pl.type);
    TEST_ASSERT_EQUAL_UINT8(IkePayloadType::IKE_PL_NONE, pl.next_payload);
    TEST_ASSERT_EQUAL_size_t(16, pl.body_len);

    TEST_ASSERT_FALSE(dws_ike_payload_next(&it, &pl)); // end of chain
}

void test_parse_malformed()
{
    IkePayloadIter it;
    IkePayload pl;
    // a payload claiming length 3 (< 4) is rejected
    const uint8_t bad[] = {0x00, 0x00, 0x00, 0x03, 0xff};
    dws_ike_payload_iter_init(&it, IkePayloadType::IKE_PL_NOTIFY, bad, sizeof(bad));
    TEST_ASSERT_FALSE(dws_ike_payload_next(&it, &pl));
    // a payload claiming to run past the buffer is rejected
    const uint8_t over[] = {0x00, 0x00, 0x00, 0x40, 0x01};
    dws_ike_payload_iter_init(&it, IkePayloadType::IKE_PL_NOTIFY, over, sizeof(over));
    TEST_ASSERT_FALSE(dws_ike_payload_next(&it, &pl));
    // notify body shorter than the fixed 4-byte prefix
    IkeProtocol proto = IkeProtocol::IKE_PROTO_NONE;
    uint16_t type = 0;
    const uint8_t *spi = nullptr, *d = nullptr;
    uint8_t ss = 0;
    size_t dl = 0;
    const uint8_t short_notify[] = {0x00, 0x00};
    TEST_ASSERT_FALSE(dws_ike_notify_parse(short_notify, sizeof(short_notify), &proto, &type, &spi, &ss, &d, &dl));
}

// ── null / capacity guards ─────────────────────────────────────────────────────────────────────

void test_hdr_guards()
{
    uint8_t buf[64];
    IkeHeader h;
    fill_hdr(&h, IkePayloadType::IKE_PL_NONE, 28);
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_hdr_build(nullptr, sizeof(buf), &h));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_hdr_build(buf, sizeof(buf), nullptr));
    TEST_ASSERT_FALSE(dws_ike_hdr_parse(GV_HDR, sizeof(GV_HDR), nullptr));
    // a null buffer still clears the out struct before it fails
    IkeHeader r;
    memset(&r, 0xff, sizeof(r));
    TEST_ASSERT_FALSE(dws_ike_hdr_parse(nullptr, 64, &r));
    TEST_ASSERT_EQUAL_UINT32(0, r.length);
    TEST_ASSERT_EQUAL_UINT8(0, r.init_spi[0]);
    // patching the length needs a real buffer holding at least a header
    TEST_ASSERT_FALSE(dws_ike_set_length(nullptr, 64, 92));
    TEST_ASSERT_FALSE(dws_ike_set_length(buf, DWS_IKE_HDR_LEN - 1, 92));
}

void test_payload_iter_guards()
{
    IkePayloadIter it;
    IkePayload pl;
    dws_ike_payload_iter_init(nullptr, IkePayloadType::IKE_PL_SA, GV_FULL, sizeof(GV_FULL)); // no-op, no crash
    dws_ike_payload_iter_init(&it, IkePayloadType::IKE_PL_SA, GV_FULL + DWS_IKE_HDR_LEN,
                              sizeof(GV_FULL) - DWS_IKE_HDR_LEN);
    TEST_ASSERT_FALSE(dws_ike_payload_next(&it, nullptr));
    // a null iterator: the out payload is cleared first
    memset(&pl, 0xff, sizeof(pl));
    TEST_ASSERT_FALSE(dws_ike_payload_next(nullptr, &pl));
    TEST_ASSERT_NULL(pl.body);
    TEST_ASSERT_EQUAL_size_t(0, pl.body_len);
    TEST_ASSERT_FALSE(pl.critical);
    // an iterator over a null area
    dws_ike_payload_iter_init(&it, IkePayloadType::IKE_PL_SA, nullptr, 16);
    TEST_ASSERT_FALSE(dws_ike_payload_next(&it, &pl));
    // an area too small to hold even a generic header
    const uint8_t tiny[] = {0x00, 0x00};
    dws_ike_payload_iter_init(&it, IkePayloadType::IKE_PL_NOTIFY, tiny, sizeof(tiny));
    TEST_ASSERT_FALSE(dws_ike_payload_next(&it, &pl));
}

void test_payload_build_raw()
{
    uint8_t buf[32];
    const uint8_t body[] = {0xde, 0xad, 0xbe, 0xef};
    size_t n = dws_ike_payload_build(buf, sizeof(buf), IkePayloadType::IKE_PL_KE, false, body, sizeof(body));
    TEST_ASSERT_EQUAL_size_t(8, n);
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkePayloadType::IKE_PL_KE, buf[0]);
    TEST_ASSERT_EQUAL_UINT8(0x00, buf[1]);
    TEST_ASSERT_EQUAL_UINT8(0x00, buf[2]);
    TEST_ASSERT_EQUAL_UINT8(0x08, buf[3]);
    TEST_ASSERT_EQUAL_MEMORY(body, buf + 4, sizeof(body));
    // critical bit set
    n = dws_ike_payload_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, true, body, sizeof(body));
    TEST_ASSERT_EQUAL_size_t(8, n);
    TEST_ASSERT_EQUAL_UINT8(DWS_IKE_CRITICAL, buf[1]);
    // an empty body is just the generic header
    n = dws_ike_payload_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, false, nullptr, 0);
    TEST_ASSERT_EQUAL_size_t(4, n);
    TEST_ASSERT_EQUAL_UINT8(0x04, buf[3]);
    // guards
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_payload_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE, false, body, sizeof(body)));
    TEST_ASSERT_EQUAL_size_t(0,
                             dws_ike_payload_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, false, nullptr, 4));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_payload_build(buf, 7, IkePayloadType::IKE_PL_NONE, false, body, sizeof(body)));
}

void test_oversize_payload_lengths()
{
    // a payload whose total does not fit the 16-bit length field is refused
    std::vector<uint8_t> out(0x10008, 0);
    std::vector<uint8_t> body(0x10000, 0xab);
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_payload_build(out.data(), out.size(), IkePayloadType::IKE_PL_NONE, false, body.data(), body.size()));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_nonce_build(out.data(), out.size(), IkePayloadType::IKE_PL_NONE, body.data(), body.size()));
    // exactly at the ceiling still builds
    size_t n = dws_ike_nonce_build(out.data(), out.size(), IkePayloadType::IKE_PL_NONE, body.data(),
                                   0xFFFF - DWS_IKE_PAYLOAD_HDR_LEN);
    TEST_ASSERT_EQUAL_size_t(0xFFFF, n);
    TEST_ASSERT_EQUAL_UINT8(0xff, out[2]);
    TEST_ASSERT_EQUAL_UINT8(0xff, out[3]);
}

void test_typed_builder_guards()
{
    uint8_t buf[64];
    const uint8_t data[] = {0x01, 0x02, 0x03, 0x04};

    // null destination
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_ke_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE, IKE_DH_MODP2048, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_nonce_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_id_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE,
                                                 IkeIdType::IKE_ID_FQDN, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_auth_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE,
                                                   IkeAuthMethod::IKE_AUTH_PSK, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_cert_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE, 4, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(0,
                             dws_ike_notify_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE,
                                                  IkeProtocol::IKE_PROTO_IKE, nullptr, 0, 16388, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_delete_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE,
                                                     IkeProtocol::IKE_PROTO_IKE, 0, nullptr, 0));

    // a non-zero length with a null body
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_ke_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IKE_DH_MODP2048, nullptr, 4));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_nonce_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, nullptr, 4));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_id_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IkeIdType::IKE_ID_FQDN, nullptr, 4));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_auth_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IkeAuthMethod::IKE_AUTH_PSK, nullptr, 4));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_cert_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, 4, nullptr, 4));
    // notify: the SPI and the data are checked independently
    TEST_ASSERT_EQUAL_size_t(0,
                             dws_ike_notify_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE,
                                                  IkeProtocol::IKE_PROTO_ESP, nullptr, 4, 16388, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_notify_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE,
                                                     IkeProtocol::IKE_PROTO_ESP, nullptr, 0, 16388, nullptr, 4));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_delete_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE,
                                                     IkeProtocol::IKE_PROTO_ESP, 4, nullptr, 2));

    // capacity one byte below the framed total
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_ke_build(buf, 11, IkePayloadType::IKE_PL_NONE, IKE_DH_MODP2048, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_nonce_build(buf, 7, IkePayloadType::IKE_PL_NONE, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_id_build(buf, 11, IkePayloadType::IKE_PL_NONE, IkeIdType::IKE_ID_FQDN, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_auth_build(buf, 11, IkePayloadType::IKE_PL_NONE, IkeAuthMethod::IKE_AUTH_PSK, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_cert_build(buf, 8, IkePayloadType::IKE_PL_NONE, 4, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_notify_build(buf, 11, IkePayloadType::IKE_PL_NONE, IkeProtocol::IKE_PROTO_IKE,
                                                     nullptr, 0, 16388, data, sizeof(data)));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_delete_build(buf, 7, IkePayloadType::IKE_PL_NONE, IkeProtocol::IKE_PROTO_IKE, 0, nullptr, 0));
}

void test_builder_empty_bodies()
{
    uint8_t buf[64];
    // every variable-length builder frames an empty body
    TEST_ASSERT_EQUAL_size_t(
        8, dws_ike_ke_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IKE_DH_CURVE25519, nullptr, 0));
    TEST_ASSERT_EQUAL_UINT8(0x00, buf[4]);
    TEST_ASSERT_EQUAL_UINT8(0x1f, buf[5]); // group 31
    TEST_ASSERT_EQUAL_size_t(4, dws_ike_nonce_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, nullptr, 0));
    TEST_ASSERT_EQUAL_UINT8(0x04, buf[3]);
    TEST_ASSERT_EQUAL_size_t(
        8, dws_ike_id_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IkeIdType::IKE_ID_IPV4_ADDR, nullptr, 0));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeIdType::IKE_ID_IPV4_ADDR, buf[4]);
    TEST_ASSERT_EQUAL_size_t(8, dws_ike_auth_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE,
                                                   IkeAuthMethod::IKE_AUTH_DIGITAL_SIG, nullptr, 0));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeAuthMethod::IKE_AUTH_DIGITAL_SIG, buf[4]);
    TEST_ASSERT_EQUAL_size_t(5, dws_ike_cert_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, 4, nullptr, 0));
    TEST_ASSERT_EQUAL_UINT8(0x05, buf[3]);
}

void test_cert_build()
{
    uint8_t buf[32];
    const uint8_t der[] = {0x30, 0x82, 0x01, 0x02};
    size_t n = dws_ike_cert_build(buf, sizeof(buf), IkePayloadType::IKE_PL_AUTH, 4, der, sizeof(der));
    TEST_ASSERT_EQUAL_size_t(9, n); // generic(4) + encoding(1) + data(4)
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkePayloadType::IKE_PL_AUTH, buf[0]);
    TEST_ASSERT_EQUAL_UINT8(0x00, buf[1]);
    TEST_ASSERT_EQUAL_UINT8(0x00, buf[2]);
    TEST_ASSERT_EQUAL_UINT8(0x09, buf[3]);
    TEST_ASSERT_EQUAL_UINT8(4, buf[4]); // X.509 certificate - signature
    TEST_ASSERT_EQUAL_MEMORY(der, buf + 5, sizeof(der));
}

void test_notify_build_with_spi()
{
    uint8_t buf[32];
    const uint8_t spi[4] = {0xaa, 0xbb, 0xcc, 0xdd};
    size_t n = dws_ike_notify_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IkeProtocol::IKE_PROTO_ESP, spi, 4,
                                    16386, nullptr, 0);
    TEST_ASSERT_EQUAL_size_t(12, n); // generic(4) + proto/spisize/type(4) + spi(4)
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeProtocol::IKE_PROTO_ESP, buf[4]);
    TEST_ASSERT_EQUAL_UINT8(4, buf[5]);
    TEST_ASSERT_EQUAL_UINT8(0x40, buf[6]);
    TEST_ASSERT_EQUAL_UINT8(0x02, buf[7]);
    TEST_ASSERT_EQUAL_MEMORY(spi, buf + 8, 4);

    IkeProtocol proto = IkeProtocol::IKE_PROTO_NONE;
    uint16_t type = 0;
    uint8_t ss = 0;
    const uint8_t *pspi = nullptr, *d = nullptr;
    size_t dl = 1;
    TEST_ASSERT_TRUE(dws_ike_notify_parse(buf + 4, n - 4, &proto, &type, &pspi, &ss, &d, &dl));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeProtocol::IKE_PROTO_ESP, (uint8_t)proto);
    TEST_ASSERT_EQUAL_UINT16(16386, type);
    TEST_ASSERT_EQUAL_UINT8(4, ss);
    TEST_ASSERT_EQUAL_MEMORY(spi, pspi, 4);
    TEST_ASSERT_EQUAL_size_t(0, dl);
}

void test_delete_build_with_spis()
{
    uint8_t buf[32];
    const uint8_t spis[8] = {1, 2, 3, 4, 5, 6, 7, 8};
    size_t n =
        dws_ike_delete_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, IkeProtocol::IKE_PROTO_ESP, 4, spis, 2);
    TEST_ASSERT_EQUAL_size_t(16, n); // generic(4) + proto/spisize/count(4) + 2 * 4
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeProtocol::IKE_PROTO_ESP, buf[4]);
    TEST_ASSERT_EQUAL_UINT8(4, buf[5]);
    TEST_ASSERT_EQUAL_UINT8(0x00, buf[6]);
    TEST_ASSERT_EQUAL_UINT8(0x02, buf[7]);
    TEST_ASSERT_EQUAL_MEMORY(spis, buf + 8, 8);

    IkeProtocol proto = IkeProtocol::IKE_PROTO_NONE;
    uint8_t ss = 0;
    uint16_t num = 0;
    const uint8_t *list = nullptr;
    TEST_ASSERT_TRUE(dws_ike_delete_parse(buf + 4, n - 4, &proto, &ss, &num, &list));
    TEST_ASSERT_EQUAL_UINT8(4, ss);
    TEST_ASSERT_EQUAL_UINT16(2, num);
    TEST_ASSERT_EQUAL_MEMORY(spis, list, 8);
}

void test_sk_build_variants()
{
    uint8_t buf[64];
    const uint8_t blob[4] = {1, 2, 3, 4};
    // every component is optional: an empty envelope is just the generic header
    size_t n = dws_ike_sk_build(buf, sizeof(buf), IkePayloadType::IKE_PL_IDI, nullptr, 0, nullptr, 0, nullptr, 0);
    TEST_ASSERT_EQUAL_size_t(4, n);
    TEST_ASSERT_EQUAL_UINT8(0x04, buf[3]);
    // a length without its buffer is refused, component by component
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_sk_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_IDI, blob, 4, blob, 4, blob, 4));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_sk_build(buf, sizeof(buf), IkePayloadType::IKE_PL_IDI, nullptr, 4, nullptr, 0, nullptr, 0));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_sk_build(buf, sizeof(buf), IkePayloadType::IKE_PL_IDI, blob, 4, nullptr, 4, nullptr, 0));
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_sk_build(buf, sizeof(buf), IkePayloadType::IKE_PL_IDI, blob, 4, blob, 4, nullptr, 4));
    // capacity one byte below the framed total
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_sk_build(buf, 15, IkePayloadType::IKE_PL_IDI, blob, 4, blob, 4, blob, 4));
}

// ── SA builder guards + an SPI-bearing proposal ────────────────────────────────────────────────

void test_sa_build_guards_and_spi()
{
    uint8_t buf[64];
    IkeTransform tr[1] = {{IkeTransformType::IKE_TRANSFORM_ENCR, IKE_ENCR_AES_GCM_16, 128}};
    const uint8_t spi[4] = {0x0a, 0x0b, 0x0c, 0x0d};

    TEST_ASSERT_EQUAL_size_t(0, dws_ike_sa_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE, 1,
                                                 IkeProtocol::IKE_PROTO_ESP, nullptr, 0, tr, 1));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_sa_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, 1,
                                                 IkeProtocol::IKE_PROTO_ESP, nullptr, 0, nullptr, 1));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_sa_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, 1,
                                                 IkeProtocol::IKE_PROTO_ESP, nullptr, 0, tr, 0));
    // an SPI size with no SPI
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_sa_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, 1,
                                                 IkeProtocol::IKE_PROTO_ESP, nullptr, 4, tr, 1));
    // capacity below the generic + proposal headers
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_sa_build(buf, 11, IkePayloadType::IKE_PL_NONE, 1, IkeProtocol::IKE_PROTO_ESP, nullptr, 0, tr, 1));
    // room for the headers but not for the first transform
    TEST_ASSERT_EQUAL_size_t(
        0, dws_ike_sa_build(buf, 12, IkePayloadType::IKE_PL_NONE, 1, IkeProtocol::IKE_PROTO_ESP, nullptr, 0, tr, 1));

    // an ESP proposal carrying a 4-byte SPI
    size_t n =
        dws_ike_sa_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, 1, IkeProtocol::IKE_PROTO_ESP, spi, 4, tr, 1);
    TEST_ASSERT_EQUAL_size_t(4 + 8 + 4 + 12, n); // generic + proposal hdr + spi + one keyed transform
    TEST_ASSERT_EQUAL_UINT8(4, buf[10]);         // spi size in the proposal header
    TEST_ASSERT_EQUAL_UINT8(1, buf[11]);         // one transform
    TEST_ASSERT_EQUAL_MEMORY(spi, buf + 12, 4);

    IkeProposalRef prop;
    TEST_ASSERT_TRUE(dws_ike_sa_first_proposal(buf + 4, n - 4, &prop));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeProtocol::IKE_PROTO_ESP, (uint8_t)prop.protocol_id);
    TEST_ASSERT_EQUAL_UINT8(4, prop.spi_size);
    TEST_ASSERT_NOT_NULL(prop.spi);
    TEST_ASSERT_EQUAL_MEMORY(spi, prop.spi, 4);
    TEST_ASSERT_EQUAL_size_t(12, prop.transforms_len);

    IkeTransformIter it;
    IkeTransformRef t;
    dws_ike_transform_iter_init(&it, &prop);
    TEST_ASSERT_TRUE(dws_ike_transform_next(&it, &t));
    TEST_ASSERT_EQUAL_UINT16(IKE_ENCR_AES_GCM_16, t.id);
    TEST_ASSERT_EQUAL_INT32(128, t.key_length);
    TEST_ASSERT_TRUE(t.last);
}

// ── traffic selector builder guards + IPv6 ─────────────────────────────────────────────────────

void test_ts_build_guards()
{
    uint8_t buf[64];
    const uint8_t s4[4] = {10, 0, 0, 0};
    const uint8_t e4[4] = {10, 0, 0, 255};
    IkeTrafficSelector sel = {IkeTsType::IKE_TS_IPV4_ADDR_RANGE, 0, 0, 65535, s4, e4, 4};

    TEST_ASSERT_EQUAL_size_t(0, dws_ike_ts_build(nullptr, sizeof(buf), IkePayloadType::IKE_PL_NONE, &sel, 1));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_ts_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, nullptr, 1));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_ts_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, &sel, 0));
    // capacity below the generic + count headers, then below the first selector
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_ts_build(buf, 7, IkePayloadType::IKE_PL_NONE, &sel, 1));
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_ts_build(buf, 23, IkePayloadType::IKE_PL_NONE, &sel, 1));
    // an address length that is neither 4 nor 16
    IkeTrafficSelector bad = sel;
    bad.addr_len = 8;
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_ts_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, &bad, 1));
    bad = sel;
    bad.start_addr = nullptr;
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_ts_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, &bad, 1));
    bad = sel;
    bad.end_addr = nullptr;
    TEST_ASSERT_EQUAL_size_t(0, dws_ike_ts_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, &bad, 1));

    // an IPv6 selector: 8 fixed bytes + two 16-byte addresses
    const uint8_t s6[16] = {0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x01};
    const uint8_t e6[16] = {0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xff};
    IkeTrafficSelector v6 = {IkeTsType::IKE_TS_IPV6_ADDR_RANGE, 6, 500, 500, s6, e6, 16};
    size_t n = dws_ike_ts_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, &v6, 1);
    TEST_ASSERT_EQUAL_size_t(4 + 4 + 8 + 32, n);
    IkeTrafficSelector got;
    TEST_ASSERT_TRUE(dws_ike_ts_get(buf + 4, n - 4, 0, &got));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeTsType::IKE_TS_IPV6_ADDR_RANGE, (uint8_t)got.ts_type);
    TEST_ASSERT_EQUAL_UINT8(6, got.ip_protocol);
    TEST_ASSERT_EQUAL_UINT16(500, got.start_port);
    TEST_ASSERT_EQUAL_size_t(16, got.addr_len);
    TEST_ASSERT_EQUAL_MEMORY(s6, got.start_addr, 16);
    TEST_ASSERT_EQUAL_MEMORY(e6, got.end_addr, 16);
}

// ── parser out-param + reject paths ────────────────────────────────────────────────────────────

void test_parse_optional_outparams()
{
    // every out-param is optional, and a short body clears the ones that were supplied
    const uint8_t ke_body[] = {0x00, 0x1f, 0x00, 0x00, 0xaa, 0xbb};
    TEST_ASSERT_TRUE(dws_ike_ke_parse(ke_body, sizeof(ke_body), nullptr, nullptr, nullptr));
    TEST_ASSERT_FALSE(dws_ike_ke_parse(nullptr, sizeof(ke_body), nullptr, nullptr, nullptr));
    uint16_t group = 0xffff;
    const uint8_t *d = ke_body;
    size_t dl = 9;
    TEST_ASSERT_FALSE(dws_ike_ke_parse(ke_body, 3, &group, &d, &dl));
    TEST_ASSERT_EQUAL_UINT16(0, group);
    TEST_ASSERT_NULL(d);
    TEST_ASSERT_EQUAL_size_t(0, dl);

    const uint8_t id_body[] = {0x02, 0x00, 0x00, 0x00, 'a', 'b'};
    TEST_ASSERT_TRUE(dws_ike_id_parse(id_body, sizeof(id_body), nullptr, nullptr, nullptr));
    TEST_ASSERT_FALSE(dws_ike_id_parse(nullptr, sizeof(id_body), nullptr, nullptr, nullptr));
    IkeIdType id_type = IkeIdType::IKE_ID_KEY_ID;
    d = id_body;
    dl = 9;
    TEST_ASSERT_FALSE(dws_ike_id_parse(id_body, 3, &id_type, &d, &dl));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeIdType::IKE_ID_RESERVED, (uint8_t)id_type);
    TEST_ASSERT_NULL(d);
    TEST_ASSERT_EQUAL_size_t(0, dl);

    const uint8_t auth_body[] = {0x02, 0x00, 0x00, 0x00, 0xde, 0xad};
    TEST_ASSERT_TRUE(dws_ike_auth_parse(auth_body, sizeof(auth_body), nullptr, nullptr, nullptr));
    TEST_ASSERT_FALSE(dws_ike_auth_parse(nullptr, sizeof(auth_body), nullptr, nullptr, nullptr));
    IkeAuthMethod method = IkeAuthMethod::IKE_AUTH_PSK;
    d = auth_body;
    dl = 9;
    TEST_ASSERT_FALSE(dws_ike_auth_parse(auth_body, 3, &method, &d, &dl));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeAuthMethod::IKE_AUTH_RESERVED, (uint8_t)method);
    TEST_ASSERT_NULL(d);
    TEST_ASSERT_EQUAL_size_t(0, dl);

    const uint8_t notify_body[] = {0x00, 0x00, 0x40, 0x04, 0xde, 0xad};
    TEST_ASSERT_TRUE(
        dws_ike_notify_parse(notify_body, sizeof(notify_body), nullptr, nullptr, nullptr, nullptr, nullptr, nullptr));
    TEST_ASSERT_FALSE(
        dws_ike_notify_parse(nullptr, sizeof(notify_body), nullptr, nullptr, nullptr, nullptr, nullptr, nullptr));

    const uint8_t delete_body[] = {0x01, 0x00, 0x00, 0x00};
    TEST_ASSERT_TRUE(dws_ike_delete_parse(delete_body, sizeof(delete_body), nullptr, nullptr, nullptr, nullptr));
    TEST_ASSERT_FALSE(dws_ike_delete_parse(nullptr, sizeof(delete_body), nullptr, nullptr, nullptr, nullptr));
    IkeProtocol proto = IkeProtocol::IKE_PROTO_ESP;
    uint8_t ss = 0xff;
    uint16_t num = 0xff;
    const uint8_t *spis = delete_body;
    TEST_ASSERT_FALSE(dws_ike_delete_parse(delete_body, 3, &proto, &ss, &num, &spis));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeProtocol::IKE_PROTO_NONE, (uint8_t)proto);
    TEST_ASSERT_EQUAL_UINT8(0, ss);
    TEST_ASSERT_EQUAL_UINT16(0, num);
    TEST_ASSERT_NULL(spis);
}

void test_notify_parse_spi()
{
    // proto ESP, 4-byte SPI, type 16389, 2 bytes of notification data
    const uint8_t body[] = {0x03, 0x04, 0x40, 0x05, 0xde, 0xad, 0xbe, 0xef, 0x11, 0x22};
    IkeProtocol proto = IkeProtocol::IKE_PROTO_NONE;
    uint16_t type = 0;
    uint8_t ss = 0;
    const uint8_t *spi = nullptr, *d = nullptr;
    size_t dl = 0;
    TEST_ASSERT_TRUE(dws_ike_notify_parse(body, sizeof(body), &proto, &type, &spi, &ss, &d, &dl));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeProtocol::IKE_PROTO_ESP, (uint8_t)proto);
    TEST_ASSERT_EQUAL_UINT8(4, ss);
    TEST_ASSERT_EQUAL_UINT16(16389, type);
    TEST_ASSERT_EQUAL_PTR(body + 4, spi);
    TEST_ASSERT_EQUAL_size_t(2, dl);
    TEST_ASSERT_EQUAL_MEMORY(body + 8, d, 2);
    // an SPI size that runs past the body
    const uint8_t trunc[] = {0x03, 0x08, 0x40, 0x05};
    TEST_ASSERT_FALSE(dws_ike_notify_parse(trunc, sizeof(trunc), &proto, &type, &spi, &ss, &d, &dl));
}

void test_delete_parse_spis()
{
    // 2 SPIs of 4 bytes
    const uint8_t body[] = {0x03, 0x04, 0x00, 0x02, 1, 2, 3, 4, 5, 6, 7, 8};
    IkeProtocol proto = IkeProtocol::IKE_PROTO_NONE;
    uint8_t ss = 0;
    uint16_t num = 0;
    const uint8_t *spis = nullptr;
    TEST_ASSERT_TRUE(dws_ike_delete_parse(body, sizeof(body), &proto, &ss, &num, &spis));
    TEST_ASSERT_EQUAL_UINT8(4, ss);
    TEST_ASSERT_EQUAL_UINT16(2, num);
    TEST_ASSERT_EQUAL_PTR(body + 4, spis);
    // an SPI size with a zero count yields no list
    const uint8_t empty[] = {0x03, 0x04, 0x00, 0x00};
    spis = body;
    TEST_ASSERT_TRUE(dws_ike_delete_parse(empty, sizeof(empty), &proto, &ss, &num, &spis));
    TEST_ASSERT_EQUAL_UINT8(4, ss);
    TEST_ASSERT_EQUAL_UINT16(0, num);
    TEST_ASSERT_NULL(spis);
    // a count * size that runs past the body
    const uint8_t trunc[] = {0x03, 0x04, 0x00, 0x02, 1, 2, 3, 4};
    TEST_ASSERT_FALSE(dws_ike_delete_parse(trunc, sizeof(trunc), &proto, &ss, &num, &spis));
}

void test_sk_parse_variants()
{
    const uint8_t body[] = {0x11, 0x22, 0x33, 0x44};
    const uint8_t *iv = body, *ct = nullptr, *icv = body;
    size_t ctl = 0;
    // an implicit-IV / no-ICV cipher leaves the whole body as ciphertext
    TEST_ASSERT_TRUE(dws_ike_sk_parse(body, sizeof(body), 0, 0, &iv, &ct, &ctl, &icv));
    TEST_ASSERT_NULL(iv);
    TEST_ASSERT_EQUAL_PTR(body, ct);
    TEST_ASSERT_EQUAL_size_t(4, ctl);
    TEST_ASSERT_NULL(icv);
    // every out-param is optional
    TEST_ASSERT_TRUE(dws_ike_sk_parse(body, sizeof(body), 0, 0, nullptr, nullptr, nullptr, nullptr));
    // null body
    TEST_ASSERT_FALSE(dws_ike_sk_parse(nullptr, 16, 0, 0, &iv, &ct, &ctl, &icv));
}

// ── SA / proposal / transform reject paths ─────────────────────────────────────────────────────

void test_sa_proposal_malformed()
{
    IkeProposalRef prop;
    TEST_ASSERT_FALSE(dws_ike_sa_first_proposal(GV_SA + 4, sizeof(GV_SA) - 4, nullptr));
    memset(&prop, 0xff, sizeof(prop));
    TEST_ASSERT_FALSE(dws_ike_sa_first_proposal(nullptr, 24, &prop));
    TEST_ASSERT_EQUAL_UINT8(0, prop.num_transforms); // out is zeroed before the body is inspected
    TEST_ASSERT_NULL(prop.transforms);
    TEST_ASSERT_FALSE(dws_ike_sa_first_proposal(GV_SA + 4, 7, &prop));
    // a proposal length below the fixed 8-byte proposal header
    const uint8_t short_plen[] = {0x00, 0x00, 0x00, 0x04, 0x01, 0x01, 0x00, 0x01};
    TEST_ASSERT_FALSE(dws_ike_sa_first_proposal(short_plen, sizeof(short_plen), &prop));
    // a proposal length running past the SA body
    const uint8_t over_plen[] = {0x00, 0x00, 0x00, 0x20, 0x01, 0x01, 0x00, 0x01};
    TEST_ASSERT_FALSE(dws_ike_sa_first_proposal(over_plen, sizeof(over_plen), &prop));
    // an SPI that does not fit inside the proposal
    const uint8_t spi_over[] = {0x00, 0x00, 0x00, 0x08, 0x01, 0x03, 0x04, 0x01};
    TEST_ASSERT_FALSE(dws_ike_sa_first_proposal(spi_over, sizeof(spi_over), &prop));
}

void test_transform_iter_guards()
{
    IkeTransformIter it;
    IkeTransformRef t;
    dws_ike_transform_iter_init(nullptr, nullptr); // no-op, no crash
    // a null proposal leaves an empty iterator
    dws_ike_transform_iter_init(&it, nullptr);
    TEST_ASSERT_NULL(it.area);
    TEST_ASSERT_EQUAL_size_t(0, it.len);
    memset(&t, 0, sizeof(t));
    TEST_ASSERT_FALSE(dws_ike_transform_next(&it, &t));
    TEST_ASSERT_EQUAL_INT32(-1, t.key_length); // out is reset before the iterator is inspected
    TEST_ASSERT_TRUE(t.last);
    TEST_ASSERT_FALSE(dws_ike_transform_next(nullptr, &t));

    IkeProposalRef prop;
    TEST_ASSERT_TRUE(dws_ike_sa_first_proposal(GV_SA + 4, sizeof(GV_SA) - 4, &prop));
    dws_ike_transform_iter_init(&it, &prop);
    TEST_ASSERT_FALSE(dws_ike_transform_next(&it, nullptr));
    // a transform length below the fixed 8-byte transform header
    const uint8_t short_tlen[] = {0x00, 0x00, 0x00, 0x04, 0x01, 0x00, 0x00, 0x0c};
    prop.transforms = short_tlen;
    prop.transforms_len = sizeof(short_tlen);
    dws_ike_transform_iter_init(&it, &prop);
    TEST_ASSERT_FALSE(dws_ike_transform_next(&it, &t));
    // a transform length running past the transform area
    const uint8_t over_tlen[] = {0x00, 0x00, 0x00, 0x10, 0x01, 0x00, 0x00, 0x0c};
    prop.transforms = over_tlen;
    prop.transforms_len = sizeof(over_tlen);
    dws_ike_transform_iter_init(&it, &prop);
    TEST_ASSERT_FALSE(dws_ike_transform_next(&it, &t));
}

void test_transform_attributes()
{
    // transform 1 carries a TLV attribute (AF bit clear: a 2-byte length then the value), transform 2
    // carries a TV attribute that is not Key Length - neither may set key_length.
    const uint8_t area[] = {0x03, 0x00, 0x00, 0x0e, 0x01, 0x00, 0x00, 0x0c, 0x00, 0x01, 0x00, 0x02, 0xaa,
                            0xbb, 0x00, 0x00, 0x00, 0x0c, 0x03, 0x00, 0x00, 0x0c, 0x80, 0x0d, 0x00, 0x40};
    IkeProposalRef prop;
    memset(&prop, 0, sizeof(prop));
    prop.transforms = area;
    prop.transforms_len = sizeof(area);

    IkeTransformIter it;
    IkeTransformRef t;
    dws_ike_transform_iter_init(&it, &prop);
    TEST_ASSERT_TRUE(dws_ike_transform_next(&it, &t));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeTransformType::IKE_TRANSFORM_ENCR, (uint8_t)t.type);
    TEST_ASSERT_EQUAL_UINT16(IKE_ENCR_AES_CBC, t.id);
    TEST_ASSERT_EQUAL_INT32(-1, t.key_length);
    TEST_ASSERT_FALSE(t.last);
    TEST_ASSERT_TRUE(dws_ike_transform_next(&it, &t));
    TEST_ASSERT_EQUAL_UINT8((uint8_t)IkeTransformType::IKE_TRANSFORM_INTEG, (uint8_t)t.type);
    TEST_ASSERT_EQUAL_UINT16(IKE_INTEG_HMAC_SHA2_256_128, t.id);
    TEST_ASSERT_EQUAL_INT32(-1, t.key_length); // TV attribute 13 is not Key Length
    TEST_ASSERT_TRUE(t.last);
    TEST_ASSERT_FALSE(dws_ike_transform_next(&it, &t));
}

// ── traffic selector reject paths ──────────────────────────────────────────────────────────────

void test_ts_parse_malformed()
{
    IkeTrafficSelector got;
    const uint8_t tiny[] = {0x01, 0x00, 0x00};
    TEST_ASSERT_EQUAL_UINT8(0, dws_ike_ts_count(nullptr, 8));
    TEST_ASSERT_EQUAL_UINT8(0, dws_ike_ts_count(tiny, sizeof(tiny)));
    TEST_ASSERT_FALSE(dws_ike_ts_get(tiny, sizeof(tiny), 0, nullptr));
    memset(&got, 0xff, sizeof(got));
    TEST_ASSERT_FALSE(dws_ike_ts_get(nullptr, 8, 0, &got));
    TEST_ASSERT_NULL(got.start_addr); // out is zeroed before the body is inspected
    TEST_ASSERT_FALSE(dws_ike_ts_get(tiny, sizeof(tiny), 0, &got));
    // a selector header past the end of the body
    const uint8_t cut[] = {0x01, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x10};
    TEST_ASSERT_FALSE(dws_ike_ts_get(cut, sizeof(cut), 0, &got));
    // a selector length below the fixed 8-byte selector header
    const uint8_t short_sel[] = {0x01, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00};
    TEST_ASSERT_FALSE(dws_ike_ts_get(short_sel, sizeof(short_sel), 0, &got));
    // a selector length running past the body
    const uint8_t over_sel[] = {0x01, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00};
    TEST_ASSERT_FALSE(dws_ike_ts_get(over_sel, sizeof(over_sel), 0, &got));
    // an odd address-byte count cannot split into a start and an end address
    const uint8_t odd_sel[] = {0x01, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x09,
                               0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    TEST_ASSERT_FALSE(dws_ike_ts_get(odd_sel, sizeof(odd_sel), 0, &got));
}

void test_ts_get_second_selector()
{
    uint8_t buf[96];
    const uint8_t s1[4] = {10, 0, 0, 1};
    const uint8_t e1[4] = {10, 0, 0, 50};
    const uint8_t s2[4] = {192, 168, 1, 1};
    const uint8_t e2[4] = {192, 168, 1, 254};
    IkeTrafficSelector sels[2] = {{IkeTsType::IKE_TS_IPV4_ADDR_RANGE, 6, 80, 80, s1, e1, 4},
                                  {IkeTsType::IKE_TS_IPV4_ADDR_RANGE, 17, 0, 65535, s2, e2, 4}};
    size_t n = dws_ike_ts_build(buf, sizeof(buf), IkePayloadType::IKE_PL_NONE, sels, 2);
    TEST_ASSERT_EQUAL_size_t(4 + 4 + 2 * 16, n);
    TEST_ASSERT_EQUAL_UINT8(2, dws_ike_ts_count(buf + 4, n - 4));
    IkeTrafficSelector got;
    // index 1 walks past selector 0
    TEST_ASSERT_TRUE(dws_ike_ts_get(buf + 4, n - 4, 1, &got));
    TEST_ASSERT_EQUAL_UINT8(17, got.ip_protocol);
    TEST_ASSERT_EQUAL_UINT16(0, got.start_port);
    TEST_ASSERT_EQUAL_UINT16(65535, got.end_port);
    TEST_ASSERT_EQUAL_MEMORY(s2, got.start_addr, 4);
    TEST_ASSERT_EQUAL_MEMORY(e2, got.end_addr, 4);
    TEST_ASSERT_FALSE(dws_ike_ts_get(buf + 4, n - 4, 2, &got));
}

// ── framing ceilings: the widest payload each builder can emit ─────────────────────────────────

void test_sa_build_widest_proposal()
{
    // The widest SA this builder can emit - a 255-byte SPI and 255 keyed (12-byte) transforms,
    // every count being a uint8_t - still frames to 3327 bytes, far below the 16-bit length
    // ceiling the builder guards against. Pins that the guard cannot fire for any legal input.
    std::vector<IkeTransform> tr(255);
    for (size_t i = 0; i < tr.size(); i++)
        tr[i] = {IkeTransformType::IKE_TRANSFORM_ENCR, IKE_ENCR_AES_CBC, 256};
    std::vector<uint8_t> spi(255, 0x5a);
    std::vector<uint8_t> buf(0x11000, 0);

    size_t n = dws_ike_sa_build(buf.data(), buf.size(), IkePayloadType::IKE_PL_NONE, 1, IkeProtocol::IKE_PROTO_ESP,
                                spi.data(), 255, tr.data(), 255);
    const size_t prop_len = 8 + 255 + 255 * 12; // proposal hdr + spi + keyed transforms
    TEST_ASSERT_EQUAL_size_t(DWS_IKE_PAYLOAD_HDR_LEN + prop_len, n);
    TEST_ASSERT_TRUE(n <= 0xFFFF); // the ceiling the builder checks is unreachable
    TEST_ASSERT_EQUAL_UINT16((uint16_t)n, (uint16_t)((buf[2] << 8) | buf[3]));
    TEST_ASSERT_EQUAL_UINT16((uint16_t)prop_len, (uint16_t)((buf[6] << 8) | buf[7]));
    TEST_ASSERT_EQUAL_UINT8(255, buf[10]); // spi size
    TEST_ASSERT_EQUAL_UINT8(255, buf[11]); // transform count

    // the whole tree still walks back out
    IkeProposalRef prop;
    TEST_ASSERT_TRUE(dws_ike_sa_first_proposal(buf.data() + 4, n - 4, &prop));
    TEST_ASSERT_EQUAL_UINT8(255, prop.spi_size);
    TEST_ASSERT_EQUAL_UINT8(255, prop.num_transforms);
    TEST_ASSERT_EQUAL_MEMORY(spi.data(), prop.spi, 255);
    IkeTransformIter it;
    IkeTransformRef t;
    dws_ike_transform_iter_init(&it, &prop);
    int seen = 0;
    while (dws_ike_transform_next(&it, &t))
    {
        TEST_ASSERT_EQUAL_INT32(256, t.key_length);
        seen++;
    }
    TEST_ASSERT_EQUAL_INT(255, seen);
    TEST_ASSERT_TRUE(t.last); // the 255th transform closes the proposal
}

void test_ts_build_widest_selector_list()
{
    // The widest TS payload - 255 IPv6 selectors, the largest selector at 40 bytes - frames to
    // 10208 bytes, so the builder's 16-bit length ceiling cannot fire for any legal input.
    const uint8_t s6[16] = {0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x01};
    const uint8_t e6[16] = {0x20, 0x01, 0x0d, 0xb8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xff};
    std::vector<IkeTrafficSelector> sels(255);
    for (size_t i = 0; i < sels.size(); i++)
        sels[i] = {IkeTsType::IKE_TS_IPV6_ADDR_RANGE, 6, 500, 500, s6, e6, 16};
    std::vector<uint8_t> buf(0x11000, 0);

    size_t n = dws_ike_ts_build(buf.data(), buf.size(), IkePayloadType::IKE_PL_NONE, sels.data(), 255);
    TEST_ASSERT_EQUAL_size_t(4 + 4 + 255 * 40, n);
    TEST_ASSERT_TRUE(n <= 0xFFFF); // the ceiling the builder checks is unreachable
    TEST_ASSERT_EQUAL_UINT16((uint16_t)n, (uint16_t)((buf[2] << 8) | buf[3]));
    TEST_ASSERT_EQUAL_UINT8(255, dws_ike_ts_count(buf.data() + 4, n - 4));
    // the last selector is still addressable, so every one of the 255 was framed
    IkeTrafficSelector got;
    TEST_ASSERT_TRUE(dws_ike_ts_get(buf.data() + 4, n - 4, 254, &got));
    TEST_ASSERT_EQUAL_size_t(16, got.addr_len);
    TEST_ASSERT_EQUAL_MEMORY(s6, got.start_addr, 16);
    TEST_ASSERT_EQUAL_MEMORY(e6, got.end_addr, 16);
    TEST_ASSERT_EQUAL_UINT16(500, got.start_port);
}

// ── tier 2: SKEYSEED / SK_* key derivation (RFC 7296 §2.13-2.14) ───────────────────────────────
// Golden vectors from an INDEPENDENT reference (Python hmac/hashlib SHA-256), so this is a cross-impl
// KAT of prf+ and the SKEYSEED->SK_* chain, not a self-consistency check.

void test_prf_plus_kat()
{
    static const uint8_t key[32] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a,
                                    0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15,
                                    0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f};
    static const uint8_t seed[4] = {0xaa, 0xbb, 0xcc, 0xdd};
    static const uint8_t expect[70] = {
        0x50, 0x68, 0xb0, 0xbd, 0x6d, 0xb4, 0xc5, 0xd9, 0x4c, 0x52, 0xc6, 0xb0, 0x2c, 0x51, 0x7c, 0xd8, 0x56, 0x33,
        0xb7, 0xc1, 0x8e, 0x7c, 0x35, 0xac, 0x86, 0x2b, 0x4b, 0x20, 0x06, 0xa3, 0xc0, 0xbd, 0xb9, 0xbe, 0x4a, 0x9f,
        0xc9, 0xe5, 0x18, 0xd3, 0x6f, 0xa9, 0x77, 0x38, 0xc0, 0xce, 0x9a, 0x84, 0x00, 0xe2, 0x51, 0x82, 0x5e, 0xaa,
        0x87, 0xf7, 0x11, 0x28, 0x89, 0x49, 0x4d, 0x4e, 0x56, 0xbb, 0x6d, 0x24, 0x7b, 0x35, 0xfe, 0xd5};
    uint8_t out[70];
    TEST_ASSERT_TRUE(dws_ike_prf_plus(key, sizeof(key), seed, sizeof(seed), out, sizeof(out)));
    TEST_ASSERT_EQUAL_MEMORY(expect, out, sizeof(out)); // spans 3 HMAC blocks (32+32+6), last one truncated
}

void test_prf_plus_guards()
{
    uint8_t out[8];
    TEST_ASSERT_FALSE(dws_ike_prf_plus(nullptr, 1, out, 1, out, 1)); // null key
    TEST_ASSERT_FALSE(dws_ike_prf_plus(out, 1, out, 1, out, 0));     // zero out_len
    // out_len over 255 blocks fails closed (the 1-byte prf+ counter caps the chain).
    static uint8_t huge[255 * 32 + 1];
    TEST_ASSERT_FALSE(dws_ike_prf_plus(out, 1, out, 1, huge, sizeof(huge)));
}

// Compare a full derivation against the reference, then confirm the ei/er halves differ (prf+ never
// repeats a block) so the split is in the right order.
void test_derive_keys_kat_16b_nonces()
{
    static const uint8_t dh[32] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
                                   0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16,
                                   0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20};
    static const uint8_t ni[16] = {0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47,
                                   0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f};
    static const uint8_t nr[16] = {0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57,
                                   0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f};
    static const uint8_t spii[8] = {0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18};
    static const uint8_t spir[8] = {0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28};
    static const uint8_t sk_d[32] = {0x8e, 0x0b, 0x9a, 0x05, 0x9a, 0x57, 0xb5, 0x62, 0x1a, 0x6e, 0xbf,
                                     0xa6, 0x86, 0x41, 0x3f, 0x6a, 0xc9, 0x93, 0xbd, 0x59, 0xf7, 0xf0,
                                     0x7e, 0x4d, 0x66, 0xa5, 0xdf, 0x32, 0x62, 0x2f, 0x86, 0x4b};
    static const uint8_t sk_ai[32] = {0x93, 0xf4, 0x7f, 0xa7, 0x6a, 0x68, 0x92, 0x09, 0xdb, 0xd8, 0xe8,
                                      0x9c, 0x37, 0xb8, 0x3b, 0xef, 0x80, 0x04, 0x57, 0x64, 0x2f, 0xb9,
                                      0x51, 0xdc, 0xbf, 0xdb, 0xd4, 0x41, 0xd1, 0x7e, 0xbb, 0x65};
    static const uint8_t sk_ar[32] = {0x21, 0x6a, 0x3f, 0xb4, 0x29, 0x03, 0x5d, 0xec, 0xac, 0xa2, 0xd1,
                                      0x80, 0xb4, 0x9d, 0xfb, 0x1a, 0x27, 0x37, 0xdb, 0x71, 0xd9, 0x47,
                                      0xec, 0x79, 0xbf, 0x49, 0x76, 0x4e, 0xcc, 0xcb, 0xfc, 0x8c};
    static const uint8_t sk_ei[32] = {0x28, 0xcb, 0x8f, 0xc9, 0xf1, 0x00, 0x97, 0xa4, 0x58, 0x42, 0x38,
                                      0x5f, 0x94, 0x62, 0xca, 0x7a, 0xc0, 0x54, 0xc3, 0xa0, 0x22, 0x68,
                                      0x75, 0xda, 0xc5, 0x7f, 0xe4, 0x6b, 0xc0, 0x14, 0x29, 0x09};
    static const uint8_t sk_er[32] = {0x21, 0xf8, 0x53, 0x49, 0x34, 0xed, 0x79, 0x8b, 0x41, 0x3d, 0x3e,
                                      0x4c, 0x5c, 0x15, 0xed, 0x9b, 0xb4, 0x83, 0x7e, 0x49, 0x1c, 0xa5,
                                      0x46, 0x8c, 0xd9, 0xe5, 0x2a, 0x1f, 0x62, 0xce, 0x5f, 0x6d};
    static const uint8_t sk_pi[32] = {0xf7, 0x1f, 0x6f, 0x05, 0xc3, 0x2b, 0xac, 0x1e, 0x19, 0x88, 0x19,
                                      0xc4, 0xdc, 0x03, 0x18, 0x44, 0xff, 0x1a, 0x5a, 0x14, 0x54, 0xa8,
                                      0x17, 0x89, 0xe8, 0x82, 0x41, 0xa6, 0x48, 0x00, 0xad, 0x12};
    static const uint8_t sk_pr[32] = {0x7f, 0x30, 0x4c, 0x9e, 0xfb, 0xc5, 0x3a, 0x26, 0xec, 0xa5, 0xd5,
                                      0x4d, 0x35, 0x81, 0x1a, 0x41, 0x11, 0xf7, 0x6f, 0x4c, 0x19, 0xab,
                                      0x56, 0x41, 0xb2, 0x18, 0x74, 0xc2, 0x8d, 0x2f, 0x18, 0x0c};
    IkeKeyLengths lens = {32, 32, 32, 32};
    IkeKeyMaterial km;
    memset(&km, 0, sizeof(km));
    TEST_ASSERT_TRUE(dws_ike_derive_keys(dh, sizeof(dh), ni, sizeof(ni), nr, sizeof(nr), spii, spir, &lens, &km));
    TEST_ASSERT_EQUAL_size_t(32, km.sk_d_len);
    TEST_ASSERT_EQUAL_size_t(32, km.sk_a_len);
    TEST_ASSERT_EQUAL_size_t(32, km.sk_e_len);
    TEST_ASSERT_EQUAL_size_t(32, km.sk_p_len);
    TEST_ASSERT_EQUAL_MEMORY(sk_d, km.sk_d, 32);
    TEST_ASSERT_EQUAL_MEMORY(sk_ai, km.sk_ai, 32);
    TEST_ASSERT_EQUAL_MEMORY(sk_ar, km.sk_ar, 32);
    TEST_ASSERT_EQUAL_MEMORY(sk_ei, km.sk_ei, 32);
    TEST_ASSERT_EQUAL_MEMORY(sk_er, km.sk_er, 32);
    TEST_ASSERT_EQUAL_MEMORY(sk_pi, km.sk_pi, 32);
    TEST_ASSERT_EQUAL_MEMORY(sk_pr, km.sk_pr, 32);
}

// 48-byte nonces make Ni|Nr = 96 > the 64-byte HMAC block, exercising the RFC 2104 key pre-hash path;
// sk_e = 36 covers an AES-GCM (key + 4-byte salt) split length.
void test_derive_keys_kat_prehash_key()
{
    static const uint8_t dh[32] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
                                   0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16,
                                   0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20};
    static const uint8_t ni[48] = {0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b,
                                   0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27,
                                   0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33,
                                   0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f};
    static const uint8_t nr[48] = {0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0x9b,
                                   0x9c, 0x9d, 0x9e, 0x9f, 0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7,
                                   0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3,
                                   0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf};
    static const uint8_t spii[8] = {0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18};
    static const uint8_t spir[8] = {0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28};
    static const uint8_t sk_d[32] = {0x84, 0x27, 0x02, 0x9f, 0x24, 0x96, 0x92, 0xff, 0x9d, 0xaa, 0x81,
                                     0x70, 0xc1, 0xc7, 0xad, 0xdb, 0xe2, 0x50, 0xd9, 0xad, 0xe4, 0x8a,
                                     0xc1, 0x4d, 0xd7, 0x54, 0xe8, 0x77, 0x12, 0xd3, 0xef, 0x1f};
    static const uint8_t sk_ei[36] = {0x18, 0xe0, 0x8f, 0x65, 0x48, 0xb2, 0x2f, 0x64, 0x48, 0xc9, 0xdb, 0x0c,
                                      0x38, 0x87, 0x68, 0x22, 0xd7, 0x01, 0xa2, 0xac, 0x5b, 0xda, 0x06, 0x2f,
                                      0x17, 0xad, 0x16, 0x42, 0x6c, 0x40, 0x73, 0x81, 0x5c, 0xd2, 0x60, 0x02};
    static const uint8_t sk_pr[32] = {0x4e, 0xe6, 0x44, 0x0b, 0x3d, 0xf2, 0xc6, 0x3f, 0x5c, 0x3d, 0x6e,
                                      0x0a, 0x3c, 0x5c, 0xd5, 0x09, 0x7a, 0x94, 0x98, 0x1d, 0x42, 0xa1,
                                      0x8e, 0x84, 0xd9, 0x73, 0xd6, 0xdf, 0xb6, 0x1f, 0x5b, 0xe5};
    IkeKeyLengths lens = {32, 32, 36, 32};
    IkeKeyMaterial km;
    memset(&km, 0, sizeof(km));
    TEST_ASSERT_TRUE(dws_ike_derive_keys(dh, sizeof(dh), ni, sizeof(ni), nr, sizeof(nr), spii, spir, &lens, &km));
    TEST_ASSERT_EQUAL_size_t(36, km.sk_e_len);
    TEST_ASSERT_EQUAL_MEMORY(sk_d, km.sk_d, 32);
    TEST_ASSERT_EQUAL_MEMORY(sk_ei, km.sk_ei, 36);
    TEST_ASSERT_EQUAL_MEMORY(sk_pr, km.sk_pr, 32);
}

void test_derive_keys_guards()
{
    static const uint8_t buf[32] = {0};
    static const uint8_t spi[8] = {0};
    IkeKeyLengths lens = {32, 32, 32, 32};
    IkeKeyMaterial km;
    TEST_ASSERT_FALSE(dws_ike_derive_keys(nullptr, 32, buf, 16, buf, 16, spi, spi, &lens, &km)); // null dh
    TEST_ASSERT_FALSE(dws_ike_derive_keys(buf, 32, buf, 0, buf, 16, spi, spi, &lens, &km));      // zero ni
    IkeKeyLengths toobig = {DWS_IKE_SK_MAX + 1, 32, 32, 32};
    TEST_ASSERT_FALSE(dws_ike_derive_keys(buf, 32, buf, 16, buf, 16, spi, spi, &toobig, &km)); // sk_d too big
    IkeKeyLengths zero = {0, 32, 32, 32};
    TEST_ASSERT_FALSE(dws_ike_derive_keys(buf, 32, buf, 16, buf, 16, spi, spi, &zero, &km)); // zero length
}

int main()
{
    UNITY_BEGIN();
    RUN_TEST(test_hdr_build);
    RUN_TEST(test_hdr_parse);
    RUN_TEST(test_hdr_set_length);
    RUN_TEST(test_ke);
    RUN_TEST(test_nonce);
    RUN_TEST(test_notify);
    RUN_TEST(test_delete);
    RUN_TEST(test_sa_build_no_keylen);
    RUN_TEST(test_sa_build_keylen);
    RUN_TEST(test_sa_parse);
    RUN_TEST(test_id_auth);
    RUN_TEST(test_ts);
    RUN_TEST(test_sk_frame);
    RUN_TEST(test_full_build);
    RUN_TEST(test_full_chain_walk);
    RUN_TEST(test_parse_malformed);
    RUN_TEST(test_hdr_guards);
    RUN_TEST(test_payload_iter_guards);
    RUN_TEST(test_payload_build_raw);
    RUN_TEST(test_oversize_payload_lengths);
    RUN_TEST(test_typed_builder_guards);
    RUN_TEST(test_builder_empty_bodies);
    RUN_TEST(test_cert_build);
    RUN_TEST(test_notify_build_with_spi);
    RUN_TEST(test_delete_build_with_spis);
    RUN_TEST(test_sk_build_variants);
    RUN_TEST(test_sa_build_guards_and_spi);
    RUN_TEST(test_ts_build_guards);
    RUN_TEST(test_parse_optional_outparams);
    RUN_TEST(test_notify_parse_spi);
    RUN_TEST(test_delete_parse_spis);
    RUN_TEST(test_sk_parse_variants);
    RUN_TEST(test_sa_proposal_malformed);
    RUN_TEST(test_transform_iter_guards);
    RUN_TEST(test_transform_attributes);
    RUN_TEST(test_ts_parse_malformed);
    RUN_TEST(test_ts_get_second_selector);
    RUN_TEST(test_sa_build_widest_proposal);
    RUN_TEST(test_ts_build_widest_selector_list);
    // tier 2: SKEYSEED / SK_* key derivation (RFC 7296 §2.13-2.14)
    RUN_TEST(test_prf_plus_kat);
    RUN_TEST(test_prf_plus_guards);
    RUN_TEST(test_derive_keys_kat_16b_nonces);
    RUN_TEST(test_derive_keys_kat_prehash_key);
    RUN_TEST(test_derive_keys_guards);
    return UNITY_END();
}
