// Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Unit tests for the OIDC RS256 ID-token verifier (services/oidc). Vectors are
// real RSA-2048 tokens signed with openssl (scratchpad/gen_oidc.sh); the JWKS
// carries the matching public key (n, e). Exercises the happy path, claim
// extraction, aud-as-array, and every rejection (alg, signature, iss, aud, exp,
// missing key, malformed).

#include "network_drivers/session/scratch.h"
#include "services/oidc/oidc.h"
#include <stdio.h>
#include <string.h>
#include <unity.h>

// --- generated by gen_oidc.sh (RSA-2048, RS256) ---
static const char *K_TOK_VALID =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2V5LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlIiwiYXVkIj"
    "oiY2xpZW50LTEyMyIsInN1YiI6InVzZXItNDIiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjQxMDI0"
    "NDQ4MDB9.QBKta3RxQh8K5FiNUL6ZJemBvIGmDsgZFhF5FbEkjcmbgNsbPZsLl70N0UFwGbsAY5sGoUZxPhWdl-_VT2nXQnwbCVqIrztVibBj4wlwL"
    "e_jY28M5OLf9t3mT5YaxWmV2FWUS_2yTYBEY96CweeoEeX_oSUSOJZyxZ_e8vbET9RcQU4zSx1sDwK6X9dUHZvs8QmrVCdqFP3OAUq0aqguj87Wcor"
    "YvCmB8nBVwYqmNupvRPP8bBPh9nTISEkP6uTQKVJKrnp5C6JN2puWS06G-YzX6HJW3nS2lHj3iI7_6xqD_pI0eXh720ZwzYSK6PPbn9EHiiw0WuaBt"
    "6G9QwR-Rg";
static const char *K_TOK_EXPIRED =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2V5LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlIiwiYXVkIj"
    "oiY2xpZW50LTEyMyIsInN1YiI6InVzZXItNDIiLCJpYXQiOjE1MDAwMDAwMDAsImV4cCI6MTYwMDAwMDAwMH0.maHZCcdhtKEyDG_VI55NPIQ9V8FX"
    "up9bm4-2Iylx8UGBSHIEm9AJcivxjU4mjgulmb6KW2mX7wPbEPf24p5r-vysJxNLcdItyZfFUy8opB_cF3HC_XYPibqgTf80CuYPJ5acKEoaVHNO7m"
    "9J66GFpmfFn02yL6EtacfZRkKvjEwXhVKfPsMmklLv5n4zSxNkwXkQSqm7SH9xoz3ohNWBNkglNMF-kNOC9jWWKdL58GTvecPKog43wVa9j_kS0VM8"
    "NAwihLbFAKQjSJF6bcX5yZsyYUVxtKDXP8WZnEQbsG122_xFZ6vrul4ZOtsH72J2OYK-6ilfaSEenE2cVudPvw";
static const char *K_TOK_AUDARR =
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2V5LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlIiwiYXVkIj"
    "pbIm90aGVyLWFwcCIsImNsaWVudC0xMjMiXSwic3ViIjoidSIsImlhdCI6MTcwMDAwMDAwMCwiZXhwIjo0MTAyNDQ0ODAwfQ.O0aL542aHac3DGg6"
    "2u_OmNww5Whfu-tmYIFUosW9p0bTFFa9hywtf77qkz039y-Sirj7KjUINUK7o_8U6BuLlaX0EdG0M6iBO4rs7NZo2vEP5t2yd9j9Cp9hwvkBulfCrC"
    "nHiBTEc06HXRva1ocYcQ5xcrEkY1JNPeALgIIpHyAJpwm5mGaMm04cTFEdshbBwoSpKaCnwKGEXZm8gMJDBmMlGbXZ2f3rLmxXPlo53KN2wVMvnSF-"
    "MD9O9Qwton1psUH_IJQsFrqoABXL1wc4cCmEpdeTEJtkV0uWWzgF825wl6v1KhUtxZojGHtZXf9PpH_PtGMuROGqHkid5drHKA";
static const char *K_TOK_HS256HDR =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRlc3Qta2V5LTEifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlIiwiYXVkIj"
    "oiY2xpZW50LTEyMyIsInN1YiI6InVzZXItNDIiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjQxMDI0"
    "NDQ4MDB9.AAAA";
static const char *K_JWKS =
    "{\"keys\":[{\"kty\":\"RSA\",\"use\":\"sig\",\"kid\":\"test-key-1\",\"alg\":\"RS256\","
    "\"n\":\"owVI9J0dgUuZi6j45vERbQdj4OuB7vY-o7k6IWGdckzCfaNaeEdbaCvK7j2OpEKyKWHsgYAcqQJXbSCnQQuIvbJPNJu8iWAqwZsakKmS0Y"
    "0aP9HIaPvlMi8pN6ihVH8lutfeWVwhn-5_V_4Y5UWRJSzZXNUplH5TML2fVWlkU1XqkbZVnkyrAqK4N8ic1Is80g4JDJvMWNRR2cltCj1hjudBiLza"
    "xwCMRp6lvXV0YsYUL-Hw3gFSSDp4MiH0zkvivV1t3qq8OG9tBUcvZtrW0D7f5FP2YqV30XJko1PaCfnwl3KsiJwno4wK0hybd9ujjDSLW7DhKE88oC"
    "W0Y8YMRQ\",\"e\":\"AQAB\"}]}";

static const char *ISS = "https://issuer.example";
static const char *AUD = "client-123";
static const uint32_t NOW = 1700000100; // after iat(1700000000), before exp(4102444800)

void setUp()
{
}
void tearDown()
{
}

// JSON-parse edge guards reachable before signature verify (header parse), plus the
// scratch-exhaustion fail-closed and a JWK whose modulus decodes to nothing.
void test_oidc_parse_edge_guards()
{
    DetwsOidcKey key;
    key.loaded = false;
    TEST_ASSERT_TRUE(detws_oidc_jwks_find(K_JWKS, "test-key-1", &key));

    // Crafted headers whose "alg" value trips a find_field edge (before sig verify) -> ERR_ALG:
    // a value missing after ':', an unterminated array value, and a numeric value.
    const char *hdr_colon = "eyJhbGciOg.b.c";      // {"alg":
    const char *hdr_array = "eyJhbGciOlthYmM.b.c"; // {"alg":[abc
    const char *hdr_negnum = "eyJhbGciOi01fQ.b.c"; // {"alg":-5}
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_ALG,
                          detws_oidc_verify_with_key(hdr_colon, strlen(hdr_colon), &key, ISS, AUD, NOW, nullptr));
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_ALG,
                          detws_oidc_verify_with_key(hdr_array, strlen(hdr_array), &key, ISS, AUD, NOW, nullptr));
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_ALG,
                          detws_oidc_verify_with_key(hdr_negnum, strlen(hdr_negnum), &key, ISS, AUD, NOW, nullptr));

    // Scratch arena exhausted before the decode buffers can be borrowed -> fail closed.
    scratch_reset();
    while (scratch_alloc(256, 1))
    {
    }
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_FORMAT,
                          detws_oidc_verify_with_key(K_TOK_VALID, strlen(K_TOK_VALID), &key, ISS, AUD, NOW, nullptr));
    scratch_reset();

    // A JWK whose modulus base64url-decodes to nothing -> parse_rsa_jwk fails.
    static const char *K_JWKS_BADN = "{\"keys\":[{\"kty\":\"RSA\",\"kid\":\"bad\",\"n\":\"\",\"e\":\"AQAB\"}]}";
    DetwsOidcKey bad;
    bad.loaded = false;
    TEST_ASSERT_FALSE(detws_oidc_jwks_find(K_JWKS_BADN, "bad", &bad));
}

void test_token_kid()
{
    char kid[64];
    TEST_ASSERT_TRUE(detws_oidc_token_kid(K_TOK_VALID, strlen(K_TOK_VALID), kid, sizeof(kid)));
    TEST_ASSERT_EQUAL_STRING("test-key-1", kid);
}

void test_jwks_find()
{
    DetwsOidcKey key;
    key.loaded = false;
    TEST_ASSERT_TRUE(detws_oidc_jwks_find(K_JWKS, "test-key-1", &key));
    TEST_ASSERT_TRUE(key.loaded);
    // e = AQAB = 65537 -> 0x00 0x01 0x00 0x01 right-aligned.
    TEST_ASSERT_EQUAL_HEX8(0x00, key.e[0]);
    TEST_ASSERT_EQUAL_HEX8(0x01, key.e[1]);
    TEST_ASSERT_EQUAL_HEX8(0x00, key.e[2]);
    TEST_ASSERT_EQUAL_HEX8(0x01, key.e[3]);
}

void test_jwks_find_missing_kid_fails()
{
    DetwsOidcKey key;
    key.loaded = false;
    TEST_ASSERT_FALSE(detws_oidc_jwks_find(K_JWKS, "nope", &key));
}

void test_verify_valid_token_and_claims()
{
    DetwsOidcClaims c;
    int rc = detws_oidc_verify(K_TOK_VALID, strlen(K_TOK_VALID), K_JWKS, ISS, AUD, NOW, &c);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_OK, rc);
    TEST_ASSERT_EQUAL_STRING("user-42", c.sub);
    TEST_ASSERT_EQUAL_STRING("alice@example.com", c.email);
    TEST_ASSERT_TRUE(c.iat == 1700000000LL);
    TEST_ASSERT_TRUE(c.exp == 4102444800LL); // > 2^31: requires 64-bit claims
}

void test_verify_aud_array()
{
    int rc = detws_oidc_verify(K_TOK_AUDARR, strlen(K_TOK_AUDARR), K_JWKS, ISS, AUD, NOW, nullptr);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_OK, rc); // "client-123" is one element of the aud array
}

void test_reject_expired()
{
    int rc = detws_oidc_verify(K_TOK_EXPIRED, strlen(K_TOK_EXPIRED), K_JWKS, ISS, AUD, NOW, nullptr);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_EXPIRED, rc);
}

void test_reject_wrong_issuer()
{
    int rc = detws_oidc_verify(K_TOK_VALID, strlen(K_TOK_VALID), K_JWKS, "https://evil.example", AUD, NOW, nullptr);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_ISS, rc);
}

void test_reject_wrong_audience()
{
    int rc = detws_oidc_verify(K_TOK_VALID, strlen(K_TOK_VALID), K_JWKS, ISS, "other-client", NOW, nullptr);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_AUD, rc);
}

void test_reject_non_rs256_header()
{
    int rc = detws_oidc_verify(K_TOK_HS256HDR, strlen(K_TOK_HS256HDR), K_JWKS, ISS, AUD, NOW, nullptr);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_ALG, rc);
}

void test_reject_tampered_payload()
{
    char tok[1024];
    strcpy(tok, K_TOK_VALID);
    char *dot = strchr(tok, '.'); // end of header
    char *c = dot + 6;            // a byte inside the payload segment
    *c = (*c == 'A') ? 'B' : 'A'; // flip to a different valid base64url char
    int rc = detws_oidc_verify(tok, strlen(tok), K_JWKS, ISS, AUD, NOW, nullptr);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_SIGNATURE, rc);
}

void test_reject_tampered_signature()
{
    char tok[1024];
    strcpy(tok, K_TOK_VALID);
    char *sig = strrchr(tok, '.') + 1; // first char of the signature segment
    *sig = (*sig == 'Q') ? 'R' : 'Q';  // flip a meaningful (non-padding) base64url char
    int rc = detws_oidc_verify(tok, strlen(tok), K_JWKS, ISS, AUD, NOW, nullptr);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_SIGNATURE, rc);
}

void test_reject_unknown_key()
{
    // JWKS whose only key has a different kid than the token's.
    const char *other = "{\"keys\":[{\"kty\":\"RSA\",\"kid\":\"different\",\"n\":\"AQAB\",\"e\":\"AQAB\"}]}";
    int rc = detws_oidc_verify(K_TOK_VALID, strlen(K_TOK_VALID), other, ISS, AUD, NOW, nullptr);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_KEY, rc);
}

void test_reject_malformed()
{
    // No kid extractable -> the sole JWKS key is selected, then the token shape
    // fails to split into three segments.
    int rc = detws_oidc_verify("not-a-jwt", 9, K_JWKS, ISS, AUD, NOW, nullptr);
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_FORMAT, rc);
}

// token_kid rejects null args, a zero-cap output and a header segment that does not
// base64url-decode.
void test_token_kid_guards()
{
    char kid[64];
    TEST_ASSERT_FALSE(detws_oidc_token_kid(nullptr, 10, kid, sizeof(kid)));
    TEST_ASSERT_FALSE(detws_oidc_token_kid("a.b.c", 5, nullptr, sizeof(kid)));
    TEST_ASSERT_FALSE(detws_oidc_token_kid("a.b.c", 5, kid, 0));
    TEST_ASSERT_FALSE(detws_oidc_token_kid("A.payload.sig", 13, kid, sizeof(kid))); // 1-char header
}

// jwks_find rejects null args, a document with no keys array, an unterminated key
// object, and a key whose kid matches but is unusable (no modulus).
void test_jwks_find_guards()
{
    DetwsOidcKey key;
    key.loaded = false;
    TEST_ASSERT_FALSE(detws_oidc_jwks_find(nullptr, "k", &key));
    TEST_ASSERT_FALSE(detws_oidc_jwks_find("{\"keys\":[]}", "k", nullptr));
    TEST_ASSERT_FALSE(detws_oidc_jwks_find("{\"foo\":1}", "k", &key));                    // no keys array
    TEST_ASSERT_FALSE(detws_oidc_jwks_find("{\"keys\":[{\"kid\":\"x\"", "x", &key));      // unterminated object
    TEST_ASSERT_FALSE(detws_oidc_jwks_find("{\"keys\":[{\"kid\":\"k1\"}]}", "k1", &key)); // kid matches, no n/e
}

// verify_with_key rejects a null / unloaded key, a zero length, and a header that does
// not decode; verify() rejects tokens with the wrong number of segments and a
// wrong-length signature.
void test_verify_guards_and_malformed()
{
    DetwsOidcKey unloaded;
    unloaded.loaded = false;
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_FORMAT,
                          detws_oidc_verify_with_key("a.b.c", 5, &unloaded, ISS, AUD, NOW, nullptr));

    DetwsOidcKey key;
    key.loaded = false;
    TEST_ASSERT_TRUE(detws_oidc_jwks_find(K_JWKS, "test-key-1", &key));
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_FORMAT, detws_oidc_verify_with_key(nullptr, 5, &key, ISS, AUD, NOW, nullptr));
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_FORMAT, detws_oidc_verify_with_key("a.b.c", 0, &key, ISS, AUD, NOW, nullptr));
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_FORMAT,
                          detws_oidc_verify_with_key("A.b.c", 5, &key, ISS, AUD, NOW, nullptr)); // header decode fail

    // Wrong segment counts (one '.' / three '.').
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_FORMAT, detws_oidc_verify("aa.bb", 5, K_JWKS, ISS, AUD, NOW, nullptr));
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_FORMAT, detws_oidc_verify("a.b.c.d", 7, K_JWKS, ISS, AUD, NOW, nullptr));

    // A valid header/payload but a truncated (wrong-length) signature.
    char buf[2048];
    snprintf(buf, sizeof(buf), "%s", K_TOK_VALID);
    char *last_dot = strrchr(buf, '.');
    last_dot[6] = '\0'; // keep only 5 signature chars -> decodes to != 256 bytes
    TEST_ASSERT_EQUAL_INT(DETWS_OIDC_ERR_FORMAT, detws_oidc_verify(buf, strlen(buf), K_JWKS, ISS, AUD, NOW, nullptr));
}

// Crafted JWKS documents exercise the JSON field scanner and the RSA-JWK loader:
// an empty document, an escaped/over-long/unterminated/non-string kid, a key missing
// its exponent, and exponents that do or do not fit the 4-byte field.
void test_jwks_malformed_keys()
{
    DetwsOidcKey key;
    key.loaded = false;

    TEST_ASSERT_FALSE(detws_oidc_jwks_find("", "k", &key)); // needle longer than the document

    // escaped char inside a string value + a mismatching kid (get_str runs, then rejects).
    TEST_ASSERT_FALSE(detws_oidc_jwks_find("{\"keys\":[{\"kid\":\"a\\\\b\"}]}", "zzz", &key));
    // kid string with no closing quote.
    TEST_ASSERT_FALSE(detws_oidc_jwks_find("{\"keys\":[{\"kid\":\"abc}]}", "abc", &key));
    // kid value is not a string.
    TEST_ASSERT_FALSE(detws_oidc_jwks_find("{\"keys\":[{\"kid\":true}]}", "x", &key));

    // a kid longer than the kid buffer (get_str overflow); the key itself is usable.
    char jwks[400];
    int p = snprintf(jwks, sizeof(jwks), "{\"keys\":[{\"kid\":\"");
    for (int i = 0; i < 200; i++)
        jwks[p++] = 'a';
    snprintf(jwks + p, sizeof(jwks) - p, "\",\"n\":\"AAAA\",\"e\":\"AQAB\"}]}");
    TEST_ASSERT_TRUE(detws_oidc_jwks_find(jwks, nullptr, &key));

    // a key with a modulus but no exponent.
    TEST_ASSERT_FALSE(detws_oidc_jwks_find("{\"keys\":[{\"n\":\"AAAA\"}]}", nullptr, &key));
    // an exponent too wide for the 4-byte field.
    TEST_ASSERT_FALSE(detws_oidc_jwks_find("{\"keys\":[{\"n\":\"AAAA\",\"e\":\"AAAAAAAA\"}]}", nullptr, &key));
    // an exponent of 5 bytes with a leading zero, which is stripped and accepted.
    TEST_ASSERT_TRUE(detws_oidc_jwks_find("{\"keys\":[{\"n\":\"AAAA\",\"e\":\"AAAAAAA\"}]}", nullptr, &key));
}

int main()
{
    UNITY_BEGIN();
    RUN_TEST(test_oidc_parse_edge_guards);
    RUN_TEST(test_jwks_malformed_keys);
    RUN_TEST(test_token_kid_guards);
    RUN_TEST(test_jwks_find_guards);
    RUN_TEST(test_verify_guards_and_malformed);
    RUN_TEST(test_token_kid);
    RUN_TEST(test_jwks_find);
    RUN_TEST(test_jwks_find_missing_kid_fails);
    RUN_TEST(test_verify_valid_token_and_claims);
    RUN_TEST(test_verify_aud_array);
    RUN_TEST(test_reject_expired);
    RUN_TEST(test_reject_wrong_issuer);
    RUN_TEST(test_reject_wrong_audience);
    RUN_TEST(test_reject_non_rs256_header);
    RUN_TEST(test_reject_tampered_payload);
    RUN_TEST(test_reject_tampered_signature);
    RUN_TEST(test_reject_unknown_key);
    RUN_TEST(test_reject_malformed);
    return UNITY_END();
}
