##
# @file theme_wizard.py
# @brief Interactive terminal wizard to configure styling choices, compile assets, and print gzipped C++ hex array.
# @details Walks the user through background theme colors, container layout styling (glassmorphism), typography,
#          and optimization preferences, then utilizes process_html.py and gzip_html_to_hex.py to generate and
#          print the corresponding C++ binary array.
# @author Douglas Quigg (dstroy0, dquigg123@gmail.com)
# @date June 2026
#

import os
import sys
import subprocess
import re
from datetime import datetime

# Path references
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROCESS_SCRIPT = os.path.join(SCRIPT_DIR, "process_html.py")
GZIP_SCRIPT = os.path.join(SCRIPT_DIR, "gzip_html_to_hex.py")

DEFAULT_HTML_CONTENT = """<!DOCTYPE html>
<html>
<head>
    <title>Server Control Center</title>
</head>
<body>
    <div class="card">
        <h1>Control Panel</h1>
        <p>System Status: <strong>Online</strong></p>
        <p>Memory Usage: <strong>Static BSS (Zero Heap)</strong></p>
        <button onclick="alert('System healthy!')">Diagnostics</button>
    </div>
</body>
</html>
"""

##
# @brief Prompts the user with multiple choice questions inside the CLI.
# @param question The question to display to the user.
# @param options A list of string options to pick from.
# @param default The default option index to select if the user presses enter.
# @return The selected choice index.
#
def prompt_choice(question, options, default=1):
    print(f"\n{question}")
    for idx, opt in enumerate(options, 1):
        print(f"  {idx}. {opt}")
    
    choice_str = input(f"Select option [Default: {default}]: ").strip()
    if not choice_str:
        return default
        
    try:
        choice = int(choice_str)
        if 1 <= choice <= len(options):
            return choice
    except ValueError:
        pass
    
    print(f"Invalid input, using default option: {default}")
    return default

##
# @brief Resolves color hex values based on the preset index selected.
# @param choice The choice index (1-4).
# @return A tuple of (bg-primary, bg-secondary, border-color, accent, accent-hover).
#
def get_theme_colors(choice):
    if choice == 1:  # Slate Cyberpunk
        return "#0a0e17", "rgba(255, 255, 255, 0.03)", "rgba(255, 255, 255, 0.08)", "#3b82f6", "#2563eb"
    elif choice == 2:  # Pure Obsidian (True Black / Purple)
        return "#000000", "rgba(147, 51, 234, 0.05)", "rgba(147, 51, 234, 0.15)", "#9333ea", "#7e22ce"
    elif choice == 3:  # Emerald Forest
        return "#061f14", "rgba(16, 185, 129, 0.04)", "rgba(16, 185, 129, 0.12)", "#10b981", "#059669"
    else:  # Custom
        bg = input("Enter primary background color (HEX, e.g., #111827): ").strip() or "#111827"
        accent = input("Enter accent color (HEX, e.g., #f43f5e): ").strip() or "#f43f5e"
        accent_hover = input("Enter accent hover color (HEX, e.g., #e11d48): ").strip() or "#e11d48"
        return bg, "rgba(255, 255, 255, 0.03)", "rgba(255, 255, 255, 0.08)", accent, accent_hover

##
# @brief Generates customized CSS content block based on user theme inputs.
# @param bg Primary background color code.
# @param bg_card Card background translucency.
# @param border Border color.
# @param accent Focus accent highlight.
# @param accent_hover Accent hover highlight.
# @param glassmorphism Enable backdrop blurred styling.
# @param font_family Font selection.
# @return Full CSS text string.
#
def generate_css_content(bg, bg_card, border, accent, accent_hover, glassmorphism=True, font_family="Inter"):
    backdrop_filter = "backdrop-filter: blur(12px);\n    -webkit-backdrop-filter: blur(12px);" if glassmorphism else ""
    card_bg = bg_card if glassmorphism else "rgba(30, 41, 59, 0.95)"
    
    css = f"""/* Custom Theme Generated by Antigravity Theme Wizard */
:root {{
    --bg-primary: {bg};
    --bg-secondary: {card_bg};
    --border-color: {border};
    --text-primary: #f3f4f6;
    --text-secondary: #9ca3af;
    --accent: {accent};
    --accent-hover: {accent_hover};
    --accent-glow: rgba({", ".join(str(int(accent[i:i+2], 16)) for i in (1, 3, 5)) if accent.startswith('#') else '59, 130, 246'}, 0.3);
}}

body {{
    background-color: var(--bg-primary);
    color: var(--text-primary);
    font-family: '{font_family}', system-ui, -apple-system, sans-serif;
    margin: 0;
    padding: 2rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    box-sizing: border-box;
}}

.card {{
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    {backdrop_filter}
    border-radius: 16px;
    padding: 2.5rem;
    max-width: 480px;
    width: 100%;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}}

.card:hover {{
    transform: translateY(-4px);
    box-shadow: 0 15px 35px rgba(0, 0, 0, 0.6), 0 0 15px var(--accent-glow);
}}

h1, h2, h3 {{
    margin-top: 0;
    color: #ffffff;
    font-weight: 700;
    letter-spacing: -0.025em;
}}

p {{
    color: var(--text-secondary);
    line-height: 1.6;
}}

button {{
    background: var(--accent);
    color: #ffffff;
    border: none;
    padding: 0.75rem 1.5rem;
    font-size: 0.95rem;
    font-weight: 600;
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.2s ease;
    box-shadow: 0 4px 12px var(--accent-glow);
}}

button:hover {{
    background: var(--accent-hover);
    transform: translateY(-1px);
    box-shadow: 0 6px 16px var(--accent-glow);
}}
"""
    return css

##
# @brief Drives the wizard interface logic.
#
def run_wizard():
    print("=" * 60)
    print("      DeterministicESPAsyncWebServer - HTML Theme Wizard")
    print("=" * 60)
    
    # 1. Ask for theme template
    theme_choice = prompt_choice(
        "Choose a starter theme color palette:",
        ["Slate Cyberpunk (Dark Blue/Cyan)", "Pure Obsidian (Obsidian Black/Purple)", "Emerald Forest (Dark Green/Mint)", "Custom Colors..."],
        1
    )
    bg, card, border, accent, accent_hover = get_theme_colors(theme_choice)
    
    # 2. Ask for design style
    design_choice = prompt_choice(
        "Choose Card/Component style:",
        ["Glassmorphism (Translucent blurred backing)", "Solid Minimalist (Opaque backing)"],
        1
    )
    is_glassmorphic = (design_choice == 1)
    
    # 3. Ask for font
    font_choice = prompt_choice(
        "Choose typography font family:",
        ["Inter (Modern sans-serif)", "JetBrains Mono (Developer monospaced)", "System Font Default"],
        1
    )
    fonts = ["Inter", "JetBrains Mono", "system-ui"]
    selected_font = fonts[font_choice - 1]
    
    # 4. Ask for HTML source
    print("\nInput HTML Template:")
    html_input_path = input("Enter path to input HTML file (leave blank to generate default template): ").strip()
    
    if not html_input_path:
        html_input_path = os.path.join(SCRIPT_DIR, "..", "html", "index.html")
        os.makedirs(os.path.dirname(html_input_path), exist_ok=True)
        with open(html_input_path, "w", encoding="utf-8") as f:
            f.write(DEFAULT_HTML_CONTENT)
        print(f"-> Generated default HTML template at {html_input_path}")
    elif not os.path.exists(html_input_path):
        print(f"Error: input file '{html_input_path}' not found.")
        return
        
    # 5. Ask for Minification
    minify_choice = prompt_choice(
        "Should we minify the HTML/CSS payload?",
        ["Yes, optimize size (recommended)", "No, keep human-readable markup"],
        1
    )
    do_minify = (minify_choice == 1)
    
    # Build Custom CSS
    css_content = generate_css_content(bg, card, border, accent, accent_hover, is_glassmorphic, selected_font)
    
    # Write custom CSS to temp location
    temp_css_path = os.path.join(SCRIPT_DIR, "temp_theme.css")
    with open(temp_css_path, "w", encoding="utf-8") as f:
        f.write(css_content)
        
    # Compile output HTML path
    processed_html_path = os.path.join(SCRIPT_DIR, "..", "html", "index_processed.html")
    
    # Run process_html.py as a subprocess
    cmd_process = [
        sys.executable, PROCESS_SCRIPT,
        "--input", html_input_path,
        "--output", processed_html_path,
    ]
    if do_minify:
        cmd_process.append("--minify")
    cmd_process.extend(["--decorate-css"])
    
    with open(PROCESS_SCRIPT, "r", encoding="utf-8") as f:
        orig_process_code = f.read()
        
    # Replace the PREMIUM_CSS variable block in process_html.py
    escaped_css_content = css_content.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    modified_process_code = re.sub(
        r'PREMIUM_CSS\s*=\s*""".*?"""',
        f'PREMIUM_CSS = """{escaped_css_content}"""',
        orig_process_code,
        flags=re.DOTALL
    )
    
    try:
        # Write modified code to process_html.py
        with open(PROCESS_SCRIPT, "w", encoding="utf-8") as f:
            f.write(modified_process_code)
            
        # Run process tool
        subprocess.run(cmd_process, check=True)
    finally:
        # Restore process_html.py to its original state
        with open(PROCESS_SCRIPT, "w", encoding="utf-8") as f:
            f.write(orig_process_code)
            
    # Run gzip_html_to_hex.py
    cmd_gzip = [
        sys.executable, GZIP_SCRIPT,
        "--input", processed_html_path
    ]
    
    res = subprocess.run(cmd_gzip, capture_output=True, text=True, check=True)
    print(res.stdout)
    
    # Find the C++ Array generated file path in stdout
    match = re.search(r"C\+\+ Array generated at:\s*(.*)", res.stdout)
    if match:
        hex_file_path = match.group(1).strip()
        print("\n" + "=" * 60)
        print("          GENERATED C++ HEX ARRAY (GZIPPED HTML)")
        print("=" * 60)
        with open(hex_file_path, "r", encoding="utf-8") as f:
            hex_array = f.read()
        print(hex_array)
        print("=" * 60)
        print(f"Configuration complete. Output file saved to:\n  {hex_file_path}")
    else:
        print("Error: Could not locate generated hex array text file.")
        
    # Cleanup temp css
    if os.path.exists(temp_css_path):
        os.remove(temp_css_path)

if __name__ == "__main__":
    run_wizard()
